// GrinKingdom — fact banks for generated species.
// Keyed by each group's `facts` id. Strings may contain `{name}`, replaced
// with the species display name by the generator. Keys missing a bank (or
// banks shorter than 3 facts) fall back to GENERIC[kingdom].

const F = {
  /* ───────── VIRUSES ───────── */
  coronavirus: [
    'Spikes shaped like tiny keys let coronaviruses unlock the door into host cells.',
    'The name comes from Latin "corona" — under a microscope the spikes look like a crown.',
    '{name} is one of the largest RNA viruses, with a genome of about 30,000 letters.',
  ],
  flu: [
    'The influenza genome comes in eight separate segments that can shuffle like cards — that is why new strains keep appearing.',
    'Flu viruses are named after two surface proteins, H and N, as in "H1N1".',
    '{name} often reaches people through pigs or poultry after starting in wild water birds.',
  ],
  paramyxo: [
    'Paramyxoviruses fuse their envelope with a host cell so fast the cell barely has time to react.',
    '{name} spreads through coughs, sneezes and droplets.',
    'Measles virus, a paramyxovirus, is one of the most contagious microbes known.',
  ],
  filo: [
    'Filoviruses are long, thread-like viruses — "filum" is Latin for thread.',
    '{name} hides in bats and occasionally spills over into other mammals.',
    'A filovirus infection can shut down blood clotting, which makes it extremely dangerous.',
  ],
  rhabdo: [
    'Rhabdoviruses are shaped like tiny bullets.',
    '{name} can travel along nerve cells to reach the brain.',
    'Rhabdoviruses infect everything from mammals to fish to plants.',
  ],
  flavi: [
    'Flaviviruses are named for the Latin "flavus" — yellow — after yellow fever.',
    'Most flaviviruses ride between hosts inside mosquitoes or ticks.',
    '{name} packs its whole instruction manual into a single strand of RNA.',
  ],
  picorna: [
    'Picornaviruses are among the smallest RNA viruses — "pico" means tiny.',
    '{name} survives stomach acid and harsh conditions surprisingly well.',
    'Polio, the common cold and foot-and-mouth disease are all picornaviruses.',
  ],
  calici: [
    'Caliciviruses get their name from cup-shaped dimples on their surface.',
    '{name} spreads easily on surfaces and in food and water.',
    'Norovirus, the famous cruise-ship bug, is a calicivirus.',
  ],
  reo: [
    'Reoviruses have double-layered shells and genomes split into ten or more segments.',
    '{name} survives for a long time in water and soil.',
    'Rotavirus, a reovirus, was once the leading cause of severe diarrhea in children.',
  ],
  herpes: [
    'Herpesviruses are masters of hide-and-seek — they sleep inside nerve cells for years.',
    '{name} stays with its host for life once it moves in.',
    'Chickenpox, cold sores and glandular fever are all caused by herpesviruses.',
  ],
  pox: [
    'Poxviruses are brick-shaped giants among viruses, big enough to be seen with a light microscope.',
    '{name} replicates entirely in the cell\'s cytoplasm, outside the nucleus.',
    'Smallpox, a poxvirus, is the only human disease ever fully eradicated.',
  ],
  adeno: [
    'Adenoviruses are named after the adenoids, where they were first discovered.',
    '{name} is so sturdy it can survive on surfaces for weeks.',
    'Modified adenoviruses are used as delivery vans for some vaccines.',
  ],
  papilloma: [
    'Papillomaviruses nudge skin cells to grow faster — causing warts.',
    '{name} can sit quietly in skin for years before showing itself.',
    'Some papillomaviruses can lead to cancer, which is why there is a vaccine against them.',
  ],
  parvo: [
    'Parvoviruses are among the tiniest viruses, with only a handful of genes.',
    '{name} is built like a microscopic geodesic dome.',
    'Canine parvovirus is so hardy it can survive in a yard for months.',
  ],
  hepadna: [
    'Hepadnaviruses carry their genome as DNA but copy it through an RNA middle step.',
    '{name} targets liver cells with unusual precision.',
    'Hepadnavirus infections can last decades, sometimes leading to liver cancer.',
  ],
  retro: [
    'Retroviruses write their RNA genome back into the host\'s DNA — a molecular U-turn.',
    '{name} needs a special enzyme, reverse transcriptase, to copy itself.',
    'Around 8% of the human genome is made of ancient retrovirus leftovers.',
  ],
  bunya: [
    'Bunyaviruses are mostly carried by insects, ticks or rodents.',
    '{name} is wrapped in a fragile envelope, so it dies quickly in dry air.',
    'The bunyavirus family includes some of the most dangerous fever viruses on Earth.',
  ],
  arena: [
    'Arenaviruses get their name from "arena" — sand — because they look gritty inside.',
    '{name} lives quietly in rodents and jumps to people through droppings.',
    'Arenaviruses can cause Lassa fever, a serious illness in West Africa.',
  ],
  phage: [
    'Bacteriophages are viruses that hunt bacteria — the most numerous entities on Earth.',
    '{name} injects its genes into a bacterium and turns it into a virus factory.',
    'Doctors are reviving phages as "living antibiotics" against resistant bacteria.',
  ],
  giantvirus: [
    'Giant viruses are so big they were once mistaken for bacteria.',
    '{name} has more genes than many living cells.',
    'Some giant viruses catch their own satellite viruses — viruses of viruses!',
  ],
  plantvirus: [
    'Plant viruses move between cells through tiny channels called plasmodesmata.',
    '{name} often hitchhikes on aphids, beetles or farm tools.',
    'The first virus ever discovered, tobacco mosaic virus, is a plant virus.',
  ],
  viroid: [
    'Viroids are even simpler than viruses — just a naked loop of RNA, no coat at all.',
    '{name} infects plants and folds its RNA into a shape the cell mistakes for its own.',
    'Viroids were discovered in 1971 in sick potatoes.',
  ],

  /* ───────── ARCHAEA ───────── */
  halophile: [
    'Halophiles love salt so much they need it to survive — some live in water ten times saltier than the sea.',
    '{name} uses salt pumps to keep its inner machinery from seizing up.',
    'Blooms of halophiles can turn salt lakes a brilliant pink.',
  ],
  methanogen: [
    'Methanogens make methane gas as their exhaust — the "swamp gas" of bogs.',
    '{name} lives in oxygen-free places: swamps, deep mud and animal guts.',
    'Methanogens are ancient — their chemistry may be how life worked billions of years ago.',
  ],
  hyperthermo: [
    'Hyperthermophiles thrive above the boiling point of water, in deep-sea vents.',
    '{name} builds its proteins extra-sturdy so heat cannot unfold them.',
    'The heat record belongs to Strain 121, a microbe that grows at 121 °C.',
  ],
  thermophile: [
    'Thermophiles are heat lovers that grow best above 45 °C.',
    '{name} is a favorite of hot springs and compost heaps.',
    'The DNA-copying enzyme used in labs, Taq polymerase, comes from a thermophile.',
  ],
  acidophile: [
    'Acidophiles flourish in places that would dissolve most cells — mine runoff, acid pools, even the stomach.',
    '{name} pumps protons out constantly to keep its inside neutral.',
    'Some acidophiles eat rock, dissolving minerals for energy.',
  ],
  ammoniaox: [
    'Ammonia-oxidizing microbes turn ammonia into nitrite, the first step of the nitrogen cycle.',
    '{name} is so common that a spoonful of garden soil holds millions.',
    'These microbes quietly feed the chemistry that fertilizes the whole planet.',
  ],
  asgard: [
    'Asgard archaea are named after Norse gods — and they may be our oldest relatives.',
    '{name} carries genes once thought to be unique to complex cells.',
    'Scientists think an Asgard-like microbe swallowed a bacterium two billion years ago, starting our lineage.',
  ],
  nanoarch: [
    'Nanoarchaea are among the smallest living cells, with only about 500 genes.',
    '{name} cannot survive alone — it rides piggyback on another archaeon.',
    'Its entire genome fits in less DNA than some viruses carry.',
  ],

  /* ───────── BACTERIA ───────── */
  bacillus: [
    'Bacilli are rod-shaped and famous for their toughness.',
    '{name} can wrap itself in a spore and wait out boiling, freezing or decades of drought.',
    'Some bacilli are our friends — they make antibiotics and fermented foods.',
  ],
  bdellovibrio: [
    'Bdellovibrio is a tiny bacterial hunter that burrows into other bacteria.',
    '{name} multiplies inside its prey, then bursts out to hunt again.',
    'Scientists study it as a living weapon against antibiotic-resistant germs.',
  ],
  campylobacter: [
    'Campylobacter is the most common bacterial cause of food poisoning.',
    '{name} has a corkscrew shape and a whip-like tail at each end.',
    'It often arrives via undercooked chicken.',
  ],
  chlamydia: [
    'Chlamydia can only grow inside a living cell — it has lost the ability to live alone.',
    '{name} sneaks between hosts in tiny, tough spores.',
    'Chlamydia infects everything from people to koalas to clams.',
  ],
  chloroflexus: [
    'Chloroflexus is a green, gliding filament found in hot springs.',
    '{name} can switch between harvesting light and eating food — a rare double life.',
    'It photosynthesizes in a way unlike any other organism.',
  ],
  clostridium: [
    'Clostridia are anaerobic — oxygen is poison to them.',
    '{name} hides as a spore until conditions turn safe.',
    'The family includes tetanus and botulism... and helpful gut residents.',
  ],
  coryne: [
    'Corynebacteria are club-shaped and ubiquitous on human skin.',
    '{name} has made our armpits part of its home range.',
    'A relative of this microbe is the cause of diphtheria.',
  ],
  cyano: [
    'Cyanobacteria invented photosynthesis — they oxygenated the whole planet.',
    '{name} can bloom so thickly it is visible from space.',
    'Every chloroplast in every plant is a domesticated cyanobacterium.',
  ],
  enteric: [
    'Enteric bacteria live in the gut — ours, and every other animal\'s.',
    '{name} helps digest food and make vitamins, but a few strains cause disease.',
    'They are the workhorses of biology labs worldwide.',
  ],
  gutmicrobe: [
    'Gut microbes outnumber our own cells and weigh about as much as our brain.',
    '{name} feeds on fibre our own enzymes cannot digest.',
    'Your exact mix of gut microbes is as personal as a fingerprint.',
  ],
  lacto: [
    'Lactobacilli turn milk into yogurt and cabbage into sauerkraut.',
    '{name} makes lactic acid, which sours and preserves food.',
    'They guard the gut by making life uncomfortable for invaders.',
  ],
  legionella: [
    'Legionella hides inside amoebae in warm water — air conditioners and hot tubs included.',
    '{name} causes pneumonia when inhaled as a fine mist.',
    'It was discovered in 1976 after an outbreak at a Philadelphia convention.',
  ],
  micrococcus: [
    'Micrococci live in colonies on skin and in soil and dust.',
    '{name} can survive drying and even some radiation.',
    'They give ripening cheese part of its smell.',
  ],
  myco: [
    'Mycobacteria have waxy, waterproof coats.',
    '{name} is related to the germs behind tuberculosis and leprosy.',
    'The waxy coat makes them slow growers — and hard to kill.',
  ],
  mycoplasma: [
    'Mycoplasmas are the smallest bacteria known, with fewer than 500 genes.',
    '{name} has no cell wall at all — just a bare membrane.',
    'One mycoplasma was the first cell with a fully lab-built genome.',
  ],
  myxococcus: [
    'Myxobacteria are social — they hunt in wolf packs.',
    '{name} can gather thousands of cells into a fruiting body with spores.',
    'They dissolve other bacteria with enzymes and share the meal.',
  ],
  neisseria: [
    'Neisseria cells pair up like coffee beans.',
    '{name} grabs onto host cells with tiny grappling hooks.',
    'The family includes the causes of meningitis and gonorrhea.',
  ],
  nitrifier: [
    'Nitrifying bacteria turn ammonia into fertilizer plants can use.',
    '{name} quietly powers the nitrogen cycle in soil and oceans.',
    'Aquarium keepers rely on them to keep fish tanks healthy.',
  ],
  phototroph: [
    'Phototrophs build food from light.',
    '{name} harvests photons with pigments instead of chloroplasts.',
    'Before plants existed, phototrophic bacteria lit up the early Earth.',
  ],
  plancto: [
    'Planctomycetes are oddballs — some keep their DNA wrapped in a membrane like a nucleus.',
    '{name} lives in water and soil worldwide.',
    'They challenged old ideas about how complex cells evolved.',
  ],
  pseudomonad: [
    'Pseudomonads are supremely versatile bacteria.',
    '{name} can digest jet fuel, plastics and pesticides.',
    'They give soil its rainy smell and infected wounds their green glow.',
  ],
  rhizobium: [
    'Rhizobia set up nitrogen factories inside plant root nodules.',
    '{name} trades nitrogen for sugar with peas, beans and clover.',
    'This partnership lets farmers grow crops without fertilizer.',
  ],
  rickettsia: [
    'Rickettsiae live inside cells and ride between hosts in ticks, fleas and lice.',
    '{name} causes spotted fevers and typhus.',
    'They are close relatives of our mitochondria.',
  ],
  spirochete: [
    'Spirochetes are coiled like springs and swim with a corkscrew motion.',
    '{name} can drill through thick fluids and tissues.',
    'The family includes the causes of Lyme disease and syphilis.',
  ],
  staph: [
    'Staphylococci grow in grape-like clusters on our skin.',
    '{name} is usually harmless — until it gets into a wound.',
    'The golden strain MRSA shrugs off many antibiotics.',
  ],
  strep: [
    'Streptococci grow in chains and live in our mouths and throats.',
    '{name} can cause strep throat and scarlet fever — or help make yogurt.',
    'Some streps dissolve red blood cells in petri dishes.',
  ],
  streptomyces: [
    'Streptomyces are soil bacteria that smell like rain on warm earth.',
    '{name} makes more than half of our antibiotics.',
    'They grow as branching filaments, like a microscopic fungus.',
  ],
  sulfur: [
    'Sulfur bacteria breathe sulfur compounds the way we breathe oxygen.',
    '{name} thrives in hot springs, seabed vents and rotten-egg mud.',
    'They often form colorful mats of yellow, pink and purple.',
  ],
  verruco: [
    'Verrucomicrobia were unknown to science until the 1990s.',
    '{name} is abundant in soil, water and even human guts.',
    'They are named for their warty, bumpy surface.',
  ],
  vibrio: [
    'Vibrios are comma-shaped and love warm, salty water.',
    '{name} can glow, swim with a single tail, and sometimes make oysters unsafe.',
    'The family includes the cause of cholera.',
  ],

  /* ───────── PROTISTS ───────── */
  amoeba: [
    'Amoebas move by pouring themselves into temporary feet called pseudopods.',
    '{name} eats by wrapping around its food and digesting it inside.',
    'Some amoebas are giants, big enough to see with the naked eye.',
  ],
  apicomplexan: [
    'Apicomplexans are parasites with a drill at one end for entering cells.',
    '{name} cannot swim or eat on its own — it lives inside a host.',
    'Malaria is caused by an apicomplexan.',
  ],
  brownalga: [
    'Brown algae get their color from a pigment that soaks up blue-green light underwater.',
    '{name} builds giant forests that shelter fish and sea otters.',
    'Their slime, alginate, is used in ice cream and toothpaste.',
  ],
  charophyte: [
    'Charophytes are the green algae most like land plants.',
    '{name} is a close cousin of the lineage that became every plant on land.',
    'Their ancestors made the first steps onto shore about 500 million years ago.',
  ],
  choano: [
    'Choanoflagellates are the closest single-celled relatives of animals.',
    '{name} wears a collar of tiny beating hairs around a single flagellum.',
    'Sponges have cells that look almost exactly like them.',
  ],
  ciliate: [
    'Ciliates row through water with thousands of beating hairs.',
    '{name} is covered in cilia that double as oars and food scoops.',
    'Some ciliates keep two different kinds of nuclei in one cell.',
  ],
  diatom: [
    'Diatoms live in glass houses they build from dissolved silicon.',
    '{name} creates shells of astonishing geometric beauty.',
    'Diatoms make about a fifth of the oxygen we breathe.',
  ],
  dino: [
    'Dinoflagellates are armored, spinning single cells.',
    '{name} can make the sea glow blue at night when disturbed.',
    'Some bloom into "red tides" that poison shellfish.',
  ],
  entamoeba: [
    'Entamoebas are amoebas that live inside animals — some harmless, some not.',
    '{name} travels as a tough cyst that survives stomach acid.',
    'One species causes amoebic dysentery.',
  ],
  euglenid: [
    'Euglenids are part plant, part animal — they photosynthesize but also hunt.',
    '{name} has a red eyespot that senses the direction of light.',
    'They swim with a single whip-like flagellum.',
  ],
  foram: [
    'Foraminifera build spiral shells the size of sand grains — and smaller.',
    '{name} extends a sticky net of threads from its shell to catch food.',
    'Their fossil shells helped geologists date rocks and find oil.',
  ],
  goldenalga: [
    'Golden algae shimmer with a yellow-brown pigment.',
    '{name} can photosynthesize or hunt bacteria, whichever is easier.',
    'Some golden algae release toxins that stun fish.',
  ],
  greenalga: [
    'Green algae are the closest relatives of land plants.',
    '{name} can be a single cell or a leafy ribbon.',
    'The chloroplasts in all green plants came from their ancestors.',
  ],
  heliozoan: [
    'Heliozoans are "sun animalcules" — spheres with rays of stiff arms.',
    '{name} skewers passing prey on its rays like a pin cushion.',
    'Each ray can retract in an instant to reel food in.',
  ],
  kelp: [
    'Kelp is a brown alga that can grow half a metre a day.',
    '{name} forms underwater forests taller than most trees.',
    'Kelp forests shelter otters, fish and thousands of species.',
  ],
  kinetoplastid: [
    'Kinetoplastids pack extra DNA into a single giant mitochondrion.',
    '{name} swims with a single lashing flagellum.',
    'The family includes the parasites behind sleeping sickness.',
  ],
  protistmisc: [
    'Protists are the grab-bag kingdom of single-celled eukaryotes.',
    '{name} does not fit neatly anywhere else — which is very protist.',
    'Every protist is a complete organism in a single cell.',
  ],
  radiolaria: [
    'Radiolarians are ocean drifters with skeletons of glass.',
    '{name} builds spiky silica shells like snowflakes.',
    'Their skeletons drift to the seafloor and become siliceous ooze.',
  ],
  redalga: [
    'Red algae can photosynthesize in deep, dim water.',
    '{name} gets its color from pigments that absorb blue light.',
    'Red algae make the nori wrapped around sushi.',
  ],
  slimemold: [
    'Slime molds are single cells that gather into a creeping, decision-making blob.',
    '{name} can solve mazes and remember routes.',
    'No brain, no nerves — and yet it finds the fastest path to food.',
  ],
  testate: [
    'Testate amoebas build tiny shells around themselves.',
    '{name} glues sand grains or scales into a portable house.',
    'Their shells preserve beautifully in peat and lake mud.',
  ],
  watermold: [
    'Water molds look like fungi but are actually relatives of brown algae.',
    '{name} releases swimming spores with two tails.',
    'One water mold caused the Irish potato famine.',
  ],

  /* ───────── FUNGI ───────── */
  armillaria: [
    'Armillaria spreads underground as shoe-string strands for kilometres.',
    '{name} may be one of the largest living organisms on Earth.',
    'Its mycelium glows faintly in the dark — old-timers called it foxfire.',
  ],
  birdsnest: [
    'Bird\'s nest fungi look like tiny nests holding eggs.',
    '{name} flings its "eggs" out with the force of raindrops.',
    'Each egg is a packet of spores that sticks wherever it lands.',
  ],
  bolete: [
    'Boletes are mushrooms with pores instead of gills.',
    '{name} is a favorite partner of forest trees.',
    'Some boletes turn blue instantly when cut.',
  ],
  bracket: [
    'Bracket fungi grow sideways out of trunks like shelves.',
    '{name} can live for decades, adding a new layer each year.',
    'The ancient iceman Ötzi carried bracket fungus in his pouch.',
  ],
  breadmold: [
    'Bread molds are the black fuzz that claims forgotten loaves.',
    '{name} shoots spores from tiny stalks that aim at the light.',
    'Its spore capsules can launch with explosive force.',
  ],
  candida: [
    'Candida is a yeast that lives on and in most of us.',
    '{name} usually behaves, but can overgrow into thrush.',
    'It switches between round and filamentous forms.',
  ],
  chytrid: [
    'Chytrids are ancient fungi with swimming spores.',
    '{name} belongs to the only fungus group with flagella.',
    'One chytrid has devastated frog populations worldwide.',
  ],
  coralfungus: [
    'Coral fungi branch like underwater corals.',
    '{name} grows in fairy rings and rainbow colors.',
    'Its branched tips are where the spores form.',
  ],
  cordyceps: [
    'Cordyceps is the "zombie fungus" of the insect world.',
    '{name} grows through an insect and steers it before sprouting.',
    'The fruiting body emerges right from the insect\'s head.',
  ],
  cryptococcus: [
    'Cryptococcus wears a slimy capsule that hides it from immune cells.',
    '{name} lives in soil and pigeon droppings.',
    'It can cause meningitis in people with weak immune systems.',
  ],
  entomopathogen: [
    'Entomopathogenic fungi hunt insects from within.',
    '{name} turns its host into a spore factory.',
    'Farmers use them as natural pesticides.',
  ],
  ergot: [
    'Ergot is a fungus that poisons grain and once caused epidemics.',
    '{name} contains compounds related to LSD.',
    'It also gave us medicines, from migraine pills to childbirth drugs.',
  ],
  glowmushroom: [
    'Glowing mushrooms shine with their own green light.',
    '{name} lights up the forest floor at night.',
    'The glow attracts insects that spread its spores.',
  ],
  inkcap: [
    'Ink caps melt into black liquid as they release spores.',
    '{name} digests itself into ink in a single day.',
    'That ink was once used for writing.',
  ],
  jelly: [
    'Jelly fungi are rubbery and can dry out, then revive with rain.',
    '{name} wiggles like jelly but survives total desiccation.',
    'The "ear fungus" in hot-and-sour soup is a jelly fungus.',
  ],
  lichen: [
    'Lichens are fungi that farm algae or cyanobacteria inside their bodies.',
    '{name} is two kingdoms working as one.',
    'Lichens can survive in Antarctica and even in space experiments.',
  ],
  malassezia: [
    'Malassezia is a yeast that lives on our skin and scalp.',
    '{name} is behind dandruff in many people.',
    'It feeds on skin oils.',
  ],
  microsporidia: [
    'Microsporidia are miniature parasites, related to fungi.',
    '{name} shoots a harpoon to inject itself into a cell.',
    'They hold the record for tiny genomes among eukaryotes.',
  ],
  mold: [
    'Molds are fungi that grow as fuzzy mats of threads.',
    '{name} spreads by releasing clouds of spores.',
    'Molds break down dead things and recycle them into soil.',
  ],
  morel: [
    'Morels are prized honeycomb mushrooms of spring.',
    '{name} pops up in forests after rain.',
    'Hunters guard their morel spots like treasure.',
  ],
  mushroom: [
    'Mushrooms are the fruit of a hidden underground network.',
    '{name} pops up after rain when conditions are just right.',
    'The visible mushroom is only a tiny part of the fungus.',
  ],
  mycorrhiza: [
    'Mycorrhizal fungi trade minerals for sugar with plant roots.',
    '{name} links trees into a "wood wide web".',
    'Most plants cannot thrive without these fungal partners.',
  ],
  puffball: [
    'Puffballs fire their spores in a smoky puff.',
    '{name} can release trillions of spores when squeezed.',
    'Some giant puffballs hold enough spores to number in the trillions.',
  ],
  rust: [
    'Rust fungi make orange, dust-like spores on leaves.',
    '{name} can need two different host plants to complete its life.',
    'Wheat rust has shaped history, causing famines.',
  ],
  schizo: [
    'Schizosaccharomyces are fission yeasts that split in two.',
    '{name} is a lab superstar for studying cell division.',
    'It splits cleanly down the middle like a dividing brick.',
  ],
  smut: [
    'Smut fungi turn plant parts into black spore powder.',
    '{name} swells corn kernels into grey-black galls.',
    'In Mexico, corn smut is cooked and eaten as huitlacoche.',
  ],
  stinkhorn: [
    'Stinkhorns smell like rotting meat — on purpose.',
    '{name} lures flies that carry its spores away.',
    'They can push up through soil in a single night.',
  ],
  truffle: [
    'Truffles are underground fungi that smell irresistible to animals.',
    '{name} grows hidden among tree roots.',
    'Pigs and dogs sniff out truffles worth more than gold by weight.',
  ],
  waxcap: [
    'Waxcaps are bright, glossy grassland mushrooms.',
    '{name} signals ancient, unpolluted meadows.',
    'They shine as if lacquered.',
  ],
  yeast: [
    'Yeasts are single-celled fungi that eat sugar and exhale carbon dioxide.',
    '{name} is the engine behind bread and beer.',
    'They have been working for humans for thousands of years.',
  ],

  /* ───────── PLANTS ───────── */
  aloe: [
    'Aloes store water and healing gel in thick leaves.',
    '{name} thrives where rain is rare.',
    'The gel soothes burns and has been used for centuries.',
  ],
  bamboo: [
    'Bamboo is a giant grass that can grow a metre in a day.',
    '{name} flowers only once every few decades — all at once.',
    'Its stems are strong enough to use as scaffolding.',
  ],
  banana: [
    'Bananas are giant herbs, not trees.',
    '{name} is one of the world\'s most important food crops.',
    'Nearly every banana eaten today is a clone of every other.',
  ],
  cactus: [
    'Cacti are desert water tanks with spines instead of leaves.',
    '{name} photosynthesizes at night to save water.',
    'Some cacti live for over a century.',
  ],
  carnivorous: [
    'Carnivorous plants turned the tables on animals.',
    '{name} lures, traps and digests its prey.',
    'They live in bogs where the soil is too poor for normal plants.',
  ],
  coffee: [
    'Coffee plants grow cherries whose seeds wake up the world.',
    '{name} is farmed across the tropics.',
    'A coffee plant takes years to produce its first crop.',
  ],
  conifer: [
    'Conifers are cone-bearing evergreens.',
    '{name} keeps its needles all winter.',
    'The tallest and oldest living things on Earth are conifers.',
  ],
  duckweed: [
    'Duckweed is the world\'s smallest flowering plant.',
    '{name} can double its numbers in a day or two.',
    'It carpets ponds and feeds ducks, fish — and maybe future astronauts.',
  ],
  fern: [
    'Ferns are older than dinosaurs.',
    '{name} reproduces with dust-like spores — no flowers or seeds.',
    'Young fern leaves uncurl from tight spirals called fiddleheads.',
  ],
  flower: [
    'Flowering plants conquered the world with a clever deal: nectar for pollen delivery.',
    '{name} advertises to pollinators with color and scent.',
    'Most plants on Earth are flowering plants.',
  ],
  fruittree: [
    'Fruit trees wrap their seeds in sweet, juicy bribes.',
    '{name} relies on animals to carry its seeds away.',
    'A fruit tree can bear crops for decades.',
  ],
  ginkgo: [
    'Ginkgoes are living fossils from before the dinosaurs.',
    '{name} has fan-shaped leaves unlike any other tree.',
    'It can survive pollution, pests and even atomic blasts.',
  ],
  gourd: [
    'Gourds and squashes are among the oldest crops.',
    '{name} grows on a scrambling vine with big yellow flowers.',
    'People have grown gourds for over 10,000 years.',
  ],
  grass: [
    'Grasses are the planet\'s most successful plants.',
    '{name} feeds the world — rice, wheat and corn are grasses.',
    'Grasslands cover a quarter of the land.',
  ],
  herb: [
    'Herbs pack intense flavor and medicine into small leaves.',
    '{name} has been used in kitchens and remedies for millennia.',
    'The oils that make herbs fragrant also deter pests.',
  ],
  horsetail: [
    'Horsetails are ancient plants with jointed, hollow stems.',
    '{name} grew in coal-age forests 300 million years ago.',
    'Their stems feel rough because they contain silica.',
  ],
  mangrove: [
    'Mangroves are trees that grow in salt water.',
    '{name} stands on stilt roots and filters the sea.',
    'Mangrove forests shelter baby fish and guard coastlines.',
  ],
  moss: [
    'Mosses are tiny pioneers with no roots.',
    '{name} drinks water through its leaves.',
    'Moss can survive drying out completely, then revive with rain.',
  ],
  nightshade: [
    'Nightshades are a family of extremes — food and poison.',
    '{name} belongs to the family of tomatoes, potatoes, tobacco and deadly nightshade.',
    'Many nightshades defend themselves with powerful chemicals.',
  ],
  orchid: [
    'Orchids are the largest plant family, with over 25,000 species.',
    '{name} has flowers of astonishing shapes and tricks.',
    'Some orchids fool insects into pollinating them by mimicry.',
  ],
  palm: [
    'Palms are tropical icons with trunks and giant leaves.',
    '{name} gives coconuts, dates, oil and shade.',
    'Palms are not trees but giant relatives of grasses.',
  ],
  succulent: [
    'Succulents hoard water in fat leaves and stems.',
    '{name} can go months between drinks.',
    'Their waxy skins seal moisture inside.',
  ],
  tea: [
    'Tea plants are evergreen bushes from Asia.',
    '{name} gives us the world\'s most popular drink after water.',
    'All tea — green, black, oolong — comes from the same plant.',
  ],
  tree: [
    'Trees are the lungs and skyscrapers of the land.',
    '{name} can live for centuries, and some for millennia.',
    'A single tree can cool a street, feed birds and make oxygen.',
  ],
  waterlily: [
    'Water lilies float their leaves and flowers on still water.',
    '{name} anchors in the mud and opens its flowers by day.',
    'Their leaves are waterproof, air-filled rafts.',
  ],
  yew: [
    'Yews are slow, ancient evergreens.',
    '{name} can live for thousands of years.',
    'Almost every part of a yew is poisonous — except the red aril.',
  ],

  /* ───────── ANIMALS ───────── */
  elephant: [
    'Elephants and their kin form an ancient African mammal branch.',
    '{name} has a long, flexible snout perfectly suited to its diet.',
    'This group includes some of the most unusual mammals on Earth.',
  ],
  ape: [
    'Great apes are our closest living relatives.',
    '{name} uses tools, learns from others and recognizes itself in a mirror.',
    'Apes have no tails — that is one way to tell them from monkeys.',
  ],
  monkey: [
    'Monkeys live in troops with friendships, rivalries and politics.',
    '{name} spends much of its day foraging and grooming.',
    'Monkeys are among the most intelligent non-human animals.',
  ],
  lemur: [
    'Lemurs exist in the wild only on Madagascar.',
    '{name} is a prosimian — an older branch of the primate family.',
    'Lemurs are vital gardeners, spreading seeds through the forest.',
  ],
  tarsier: [
    'Tarsiers have the biggest eyes, for their size, of any mammal.',
    '{name} can turn its head almost all the way around.',
    'Its eyes are so big they cannot move in their sockets.',
  ],
  whale: [
    'Whales are mammals that returned to the sea millions of years ago.',
    '{name} can dive deeper than most submarines and sing across oceans.',
    'A whale\'s closest living land relative is the hippopotamus.',
  ],
  dolphin: [
    'Dolphins are small whales famous for their intelligence.',
    '{name} greets others with signature whistles — names, basically.',
    'They use echolocation to "see" with sound.',
  ],
  bigcat: [
    'Cats are born hunters with padded paws and razor focus.',
    '{name} stalks its prey in near silence, then pounces.',
    'Every cat\'s coat pattern is unique, like a fingerprint.',
  ],
  bear: [
    'Bears are some of the strongest omnivores on land.',
    '{name} has a sense of smell far better than any dog\'s.',
    'Most bears snooze through winter without truly hibernating.',
  ],
  canid: [
    'The dog family hunts with teamwork and stamina.',
    '{name} communicates with barks, howls and tail talk.',
    'Canids live on every continent except Antarctica.',
  ],
  mustelid: [
    'Weasels and their kin are small predators with huge attitudes.',
    '{name} can take down prey many times its own size.',
    'Mustelids use scent glands to mark territory and to defend themselves.',
  ],
  pinniped: [
    'Seals, sea lions and walruses are ocean-going carnivores.',
    '{name} hauls out on land or ice to rest and raise pups.',
    'They can hold their breath for astonishingly long dives.',
  ],
  equid: [
    'Horses, zebras and asses are built for running.',
    '{name} can sleep standing up and gallop within hours of birth.',
    'Zebra stripes may confuse biting flies.',
  ],
  deer: [
    'Deer are browsers and grazers with watchful eyes.',
    '{name} grows antlers (if male) and sheds them every year.',
    'A fawn\'s spotted coat hides it in dappled light.',
  ],
  bovid: [
    'Bovids — cattle, antelope, goats and sheep — are the great grazers.',
    '{name} chews its food twice thanks to a four-chambered stomach.',
    'Their horns grow all their lives and are never shed.',
  ],
  giraffe: [
    'Giraffes are the tallest animals on Earth.',
    '{name} has the same number of neck bones as you — just much longer.',
    'No two giraffes share the same spot pattern.',
  ],
  camelid: [
    'Camels and their kin are desert specialists.',
    '{name} can go for days without drinking, then gulp water fast.',
    'They walk with a rocking pace, moving both legs on one side.',
  ],
  hippo: [
    'Hippos are river giants that graze on land at night.',
    '{name} secretes a red "sunscreen" that also fights germs.',
    'Despite their bulk, hippos can outrun a human.',
  ],
  pig: [
    'Pigs are among the smartest farm animals.',
    '{name} uses its snout like a shovel and a sensor at once.',
    'Pigs wallow in mud to cool off — not because they are messy.',
  ],
  rhino: [
    'Rhinos are armored tanks of the grasslands.',
    '{name} relies on scent and hearing more than eyesight.',
    'A rhino\'s horn is made of keratin, like your fingernails.',
  ],
  tapir: [
    'Tapirs are shy forest browsers with flexible snouts.',
    '{name} loves water and will dive to escape danger.',
    'Tapir babies wear stripes and spots like pajamas.',
  ],
  squirrel: [
    'Squirrels are nature\'s forgetful gardeners.',
    '{name} buries thousands of nuts — and forgets many, planting trees.',
    'They can rotate their ankles to climb down head-first.',
  ],
  rodent: [
    'Rodents are the most numerous mammals on Earth.',
    '{name} has front teeth that never stop growing.',
    'Rodents make up about 40% of all mammal species.',
  ],
  beaver: [
    'Beavers are engineers that rebuild rivers.',
    '{name} fells trees with teeth hardened by iron.',
    'A beaver lodge has an underwater entrance for safety.',
  ],
  spiky: [
    'Spiky mammals wear armor of modified hairs.',
    '{name} rolls up or bristles when threatened.',
    'Their quills and spines are just super-stiff hair.',
  ],
  kangaroo: [
    'Kangaroos bounce on springs of tendon.',
    '{name} can leap farther than almost any animal its size.',
    'A kangaroo\'s tail works like a fifth leg.',
  ],
  marsupial: [
    'Marsupials raise their babies in a pouch.',
    '{name} is born the size of a jellybean and crawls to the pouch.',
    'Most marsupials live in Australia and the Americas.',
  ],
  sloth: [
    'Sloths live life in slow motion to save energy.',
    '{name} moves so slowly that algae grows in its fur.',
    'They climb down from trees only about once a week.',
  ],
  platypus: [
    'The platypus is a mammal that lays eggs.',
    '{name} senses prey with electrical receptors in its bill.',
    'Male platypuses carry venomous spurs on their ankles.',
  ],
  bat: [
    'Bats are the only mammals that truly fly.',
    '{name} navigates by echolocation, shouting beyond our hearing.',
    'A single bat can eat thousands of insects in a night.',
  ],
  shrew: [
    'Shrews are tiny predators with huge appetites.',
    '{name} must eat almost constantly to stay alive.',
    'Some shrews have venomous saliva.',
  ],
  mole: [
    'Moles are built for a life underground.',
    '{name} can dig tunnels at incredible speed.',
    'Moles can feel prey through the earth with their noses.',
  ],
  raptor: [
    'Birds of prey are sky hunters with telescope eyes.',
    '{name} can spot prey from far beyond human vision.',
    'Their talons and hooked beaks are precision tools.',
  ],
  owl: [
    'Owls own the night sky.',
    '{name} flies in near silence thanks to fringed feathers.',
    'Owls can turn their heads about 270 degrees.',
  ],
  parrot: [
    'Parrots are brainy birds with a talent for mimicry.',
    '{name} can solve puzzles and use tools with beak and feet.',
    'Parrots often live for decades, and some outlive their owners.',
  ],
  corvid: [
    'Crows and their kin are among the smartest animals alive.',
    '{name} can solve puzzles, plan ahead and even hold grudges.',
    'Corvids remember faces for years.',
  ],
  songbird: [
    'Songbirds learn their songs, much like we learn language.',
    '{name} practices its tune from a young age.',
    'Nearly half of all bird species are songbirds.',
  ],
  waterfowl: [
    'Ducks, geese and swans are built for water and air.',
    '{name} waterproofs its feathers with oil from a special gland.',
    'Many waterfowl migrate thousands of kilometres every year.',
  ],
  seabird: [
    'Seabirds spend most of their lives over open ocean.',
    '{name} drinks salt water and sneezes the salt out.',
    'Some seabirds stay aloft for months at a time.',
  ],
  penguin: [
    'Penguins are flightless birds that "fly" underwater.',
    '{name} can dive deeper than many submarines go.',
    'Penguins huddle together to survive Antarctic storms.',
  ],
  wading: [
    'Wading birds patrol the shallows on long legs.',
    '{name} stands still as a statue, then strikes with its bill.',
    'Long legs and long necks make them perfect shallows fishers.',
  ],
  ratite: [
    'Ratites are giant birds that traded flight for speed.',
    '{name} can sprint faster than most horses.',
    'Ratites lay the largest eggs of any living bird.',
  ],
  hummingbird: [
    'Hummingbirds are living helicopters.',
    '{name} can hover, fly backwards and even upside down.',
    'Their wings beat up to 80 times per second.',
  ],
  kingfisher: [
    'Kingfishers dive like blue arrows.',
    '{name} plunges into water to snatch fish with its dagger bill.',
    'Their eyes adjust underwater in a split second.',
  ],
  toucan: [
    'A toucan\'s beak is a built-in radiator.',
    '{name} uses its huge bill to cool off and reach fruit.',
    'The bill is light — a honeycomb of bone with air inside.',
  ],
  shark: [
    'Sharks are older than trees and dinosaurs.',
    '{name} senses the electric field of prey.',
    'Sharks never run out of teeth — new rows rotate in for life.',
  ],
  ray: [
    'Rays are flattened sharks that glide like wings.',
    '{name} is closely related to sharks, with a skeleton of cartilage.',
    'Some rays can sense electricity, and a few can shock.',
  ],
  fish: [
    'Fish were the first vertebrates, and still the most varied.',
    '{name} breathes underwater with gills.',
    'There are more fish species than all land vertebrates combined.',
  ],
  scombrid: [
    'Tunas and mackerels are torpedoes of the open sea.',
    '{name} is warm-blooded in a cold ocean — a rare trick for a fish.',
    'They cruise at highway speeds for hours on end.',
  ],
  cichlid: [
    'Cichlids are the most diverse fish family on Earth.',
    '{name} is a devoted parent, guarding eggs and fry.',
    'African lakes hold hundreds of cichlid species found nowhere else.',
  ],
  clownfish: [
    'Clownfish live safely among stinging anemones.',
    '{name} is coated in mucus that the anemone does not sting.',
    'If the female dies, the top male changes into a female.',
  ],
  herring: [
    'Herring travel in schools of millions.',
    '{name} moves as one with its school, like a silver cloud.',
    'Herring schools are so dense they can be seen from space.',
  ],
  salmon: [
    'Salmon are born in rivers and return there to spawn.',
    '{name} remembers the smell of its home stream years later.',
    'They leap waterfalls on the journey upstream.',
  ],
  characin: [
    'Characins are freshwater fish of Africa and South America.',
    '{name} is a relative of piranhas and tetras.',
    'Many characins school together for safety.',
  ],
  eel: [
    'Eels are long-distance travellers.',
    '{name} migrates thousands of kilometres to spawn.',
    'Eel larvae drift on ocean currents before finding fresh water.',
  ],
  coelacanth: [
    'Coelacanths were thought extinct for 66 million years.',
    '{name} was rediscovered alive in 1938.',
    'Its fins move like legs — a glimpse of our own deep past.',
  ],
  sturgeon: [
    'Sturgeons are living fossils from the age of dinosaurs.',
    '{name} wears armor plates instead of scales.',
    'Their eggs are prized as caviar.',
  ],
  seahorse: [
    'Seahorses are fish that swim upright.',
    '{name} has a gripping tail, a slurping snout, and no stomach.',
    'The male seahorse carries the babies.',
  ],
  puffer: [
    'Pufferfish inflate into spiky balls when scared.',
    '{name} carries one of the strongest natural toxins known.',
    'They blow themselves up with water in seconds.',
  ],
  deepsea: [
    'Deep-sea fish live in a world without sunlight.',
    '{name} makes its own light with glowing bacteria or chemicals.',
    'The deep sea is the largest habitat on Earth.',
  ],
  hagfish: [
    'Hagfish are jawless fish older than most life in the sea.',
    '{name} defends itself with a cloud of slime.',
    'They can tie themselves in knots to clean off slime.',
  ],
  lamprey: [
    'Lampreys are jawless fish with a sucker full of teeth.',
    '{name} has been around for 360 million years.',
    'Some lampreys latch onto fish as parasites.',
  ],
  frog: [
    'Frogs are ancient amphibians that begin life as tadpoles.',
    '{name} breathes through its skin as well as its lungs.',
    'Frog populations are sentinels for the health of the planet.',
  ],
  salamander: [
    'Salamanders are amphibians with extraordinary healing powers.',
    '{name} can regrow lost limbs, tails and even parts of its heart.',
    'Most salamanders never drink — they absorb water through their skin.',
  ],
  lizard: [
    'Lizards are the most successful reptiles on Earth.',
    '{name} basks in the sun to charge up its day.',
    'Many lizards can shed their tail to escape, then regrow it.',
  ],
  snake: [
    'Snakes smell with their tongues.',
    '{name} can swallow prey bigger than its own head.',
    'Snakes have no eyelids — their eyes are covered by clear scales.',
  ],
  croc: [
    'Crocodilians have barely changed since the dinosaurs.',
    '{name} has the strongest bite measured in any animal.',
    'A croc can hold its breath underwater for over an hour.',
  ],
  turtle: [
    'Turtles carry their home on their back.',
    '{name} has a shell made of bone fused to its ribs.',
    'Some sea turtles migrate across entire oceans.',
  ],
  beetle: [
    'Beetles are the most numerous animals on Earth.',
    '{name} wears armor that also covers its wings.',
    'One in four animal species is a beetle.',
  ],
  firefly: [
    'Fireflies speak in flashes of light.',
    '{name} makes light with almost no heat — nature\'s LED.',
    'Each species has its own flash code to find a mate.',
  ],
  butterfly: [
    'Butterflies taste with their feet.',
    '{name} transforms from a crawling caterpillar into a flying jewel.',
    'Their wing colors come from microscopic scales.',
  ],
  bee: [
    'Bees are the world\'s most important pollinators.',
    '{name} dances to tell hive-mates where the flowers are.',
    'A honey bee makes about a twelfth of a teaspoon of honey in her life.',
  ],
  ant: [
    'Ants are superorganisms — the colony is the real animal.',
    '{name} can carry many times its own weight.',
    'Ants farm fungus, herd aphids and wage wars.',
  ],
  hopper: [
    'Grasshoppers and their kin are built for the long jump.',
    '{name} can leap dozens of body lengths.',
    'They "sing" by rubbing legs against wings.',
  ],
  mantis: [
    'Mantises are the ninjas of the insect world.',
    '{name} can turn its head to look you in the eye.',
    'Its strike is among the fastest movements in nature.',
  ],
  dragonfly: [
    'Dragonflies are the most agile fliers on Earth.',
    '{name} can fly backwards, hover and snatch prey mid-air.',
    'They catch about 95% of the prey they chase.',
  ],
  truebug: [
    'True bugs are insects with needle-like mouthparts.',
    '{name} drinks liquids — plant sap or prey.',
    'They are the only insects scientists officially call "bugs".',
  ],
  fly: [
    'Flies are aerial acrobats with a single pair of wings.',
    '{name} reacts to threats ten times faster than we can.',
    'They taste with their feet the moment they land.',
  ],
  spider: [
    'Spiders are eight-legged engineers of silk.',
    '{name} spins silk stronger than steel, weight for weight.',
    'Spider silk can be a web, a parachute or a cradle.',
  ],
  scorpion: [
    'Scorpions have patrolled the night for over 400 million years.',
    '{name} glows under ultraviolet light.',
    'They can survive months without food.',
  ],
  tick: [
    'Ticks are arachnids that feed on blood.',
    '{name} can wait months on a blade of grass for a host.',
    'Ticks are not insects — they have eight legs.',
  ],
  crab: [
    'Crabs are armored wanderers of shore and sea.',
    '{name} walks sideways and can regrow lost claws.',
    'Some crabs wear anemones or sponges as camouflage hats.',
  ],
  shrimp: [
    'Shrimp are the clean-up crew of the sea.',
    '{name} swims backwards with a flick of its tail.',
    'Many shrimp see colors we cannot even imagine.',
  ],
  crusty: [
    'Crustaceans are the armored cousins of insects.',
    '{name} is a small but vital link in the ocean food web.',
    'Their skeletons are on the outside, and they molt to grow.',
  ],
  mantisshrimp: [
    'Mantis shrimp punch with the speed of a bullet.',
    '{name} sees colors and polarized light beyond human vision.',
    'Its strike can crack aquarium glass.',
  ],
  snail: [
    'Snails carry their homes as they slide.',
    '{name} moves on a ribbon of muscle called a foot.',
    'Many snails are both male and female at once.',
  ],
  bivalve: [
    'Bivalves are two-shelled filter feeders.',
    '{name} cleans the water as it eats.',
    'Some bivalves make pearls around irritants.',
  ],
  octopus: [
    'Octopuses are the smartest invertebrates known.',
    '{name} has nine brains — one in each arm plus a central one.',
    'It can change color, texture and shape in an instant.',
  ],
  squid: [
    'Squid are jet-propelled rockets of the sea.',
    '{name} squeezes water through a nozzle to dart backwards.',
    'Squid have three hearts pumping blue-green blood.',
  ],
  starfish: [
    'Starfish are slow-motion hunters of the seafloor.',
    '{name} pushes its stomach out through its mouth to eat.',
    'They can regrow lost arms — and sometimes a whole body.',
  ],
  jellyfish: [
    'Jellyfish are 95% water, with no brain and no heart.',
    '{name} has drifted the oceans for over 500 million years.',
    'Their sting comes from microscopic harpoons.',
  ],
  coral: [
    'Corals are tiny animals that build cities of stone.',
    '{name} is a colony of thousands of polyps working together.',
    'Coral reefs shelter a quarter of all ocean life.',
  ],
  sponge: [
    'Sponges are the simplest animals on Earth.',
    '{name} pumps water through its body to eat and breathe.',
    'Sponges have no brain, nerves or muscles — and yet they thrive.',
  ],
  earthworm: [
    'Earthworms are the plows of the soil.',
    '{name} eats its way through the earth, fertilizing as it goes.',
    'Worms can regrow lost segments.',
  ],
  tardigrade: [
    'Tardigrades are the toughest animals known.',
    '{name} can survive space, boiling, freezing and decades without water.',
    'They dry out into glassy "tuns" and wait for better times.',
  ],

  /* ───────── HUMANS ───────── */
  hominin: [
    'Hominins are the branch of apes that walked upright.',
    '{name} is known from fossils that tell the story of our origins.',
    'Stone tools and footprints give clues to how hominins lived.',
  ],
}

export const GENERIC = {
  viruses: [
    '{name} is too small to see without a microscope — thousands could fit on a pinhead.',
    'Viruses blur the line between living and non-living things.',
    '{name} can only copy itself inside the cells of a host.',
  ],
  archaea: [
    '{name} is a microbe from one of the oldest branches of life.',
    'Archaea look like bacteria but are built completely differently inside.',
    '{name} thrives in conditions that would finish off most other life.',
  ],
  bacteria: [
    '{name} is a single-celled organism found nearly everywhere on Earth.',
    'Bacteria are the oldest form of life, going back over 3.5 billion years.',
    '{name} reproduces by simply splitting in two.',
  ],
  protists: [
    '{name} is a single-celled eukaryote — a whole organism in one cell.',
    'Protists are the most varied kingdom of all, from hunters to algae.',
    '{name} lives its entire life at a microscopic scale.',
  ],
  fungi: [
    '{name} feeds by absorbing nutrients through a web of threads.',
    'Fungi are more closely related to animals than to plants.',
    '{name} plays a quiet but vital role as nature\'s recycler.',
  ],
  plants: [
    '{name} turns sunlight, water and air into food — and gives us oxygen in return.',
    'Plants are the foundation of nearly every food chain on land.',
    '{name} cannot run or hide, so it relies on clever chemistry to survive.',
  ],
  animals: [
    '{name} is a multi-celled animal that must find its own food.',
    'Animals are the kingdom of movers — from swimmers to fliers to runners.',
    '{name} senses the world with nerves and responds in the blink of an eye.',
  ],
  humans: [
    '{name} belongs to the family tree that produced modern humans.',
    'Hominins are the only apes that learned to walk on two legs.',
    '{name} is known from fossils that tell the story of our origins.',
  ],
}

/* Tagline templates per kingdom (auto-written when a seed has no tagline). */
export const TAGLINES = {
  viruses: [
    'A microscopic hijacker with a story written in RNA.',
    'Tiny, spiky and utterly single-minded.',
    'A package of genes looking for a cell to call home.',
  ],
  archaea: [
    'An extreme-conditions specialist from the oldest branch of life.',
    'A hardcore microbe that laughs at heat, salt and acid.',
    'One of the most ancient life forms on Earth.',
  ],
  bacteria: [
    'A single cell with superpowers you would never guess.',
    'The tiny engine behind soil, sea and your own gut.',
    'Small, mighty and absolutely everywhere.',
  ],
  protists: [
    'A whole organism packed into one busy cell.',
    'The ocean\'s hidden powerhouse, one cell at a time.',
    'Neither plant, animal nor fungus — and all three at once.',
  ],
  fungi: [
    'The quiet recycler that runs the forest underground.',
    'Part of the hidden web that feeds every tree.',
    'Nature\'s decomposer, medicine-maker and feast.',
  ],
  plants: [
    'A solar-powered survivor of the green kingdom.',
    'Rooted in place, but with tricks up every leaf.',
    'Quiet, patient and absolutely essential.',
  ],
  animals: [
    'A mover, a hunter, a wanderer of the living world.',
    'Born to explore the world with senses blazing.',
    'One of the animal kingdom\'s wonderful characters.',
  ],
  humans: [
    'A face from our own family album, deep in time.',
    'One of the relatives we share our story with.',
    'A fossil echo of the road that led to us.',
  ],
  /* ───────── EXPANSION WAVE 2 ───────── */
  gibbon: [
    'Gibbons are the acrobats of the ape world, swinging hand over hand at 55 km/h.',
    '{name} duets with its partner every dawn to defend a patch of forest canopy.',
    'Their extra-long arms and hook hands let them “fly” through trees without ever touching the ground.',
  ],
  sirenian: [
    'Sea cows are the only fully aquatic mammals that eat plants.',
    '{name} spends its whole life in water, surfacing every few minutes to breathe.',
    'Sirenians are more closely related to elephants than to whales or seals.',
  ],
  vulture: [
    'Vultures are nature’s cleanup crew, spotting meals from kilometres high.',
    '{name} has a stomach acid strong enough to safely digest rotting meat.',
    'A flock of vultures can strip a carcass in under an hour, stopping disease from spreading.',
  ],
  molerat: [
    'Mole-rats live like insects — a single queen rules an underground colony of workers.',
    '{name} barely feels acid burns or pepper heat, and almost never gets cancer.',
    'Mole-rats can slow their breathing to survive in air with almost no oxygen.',
  ],
  tuatara: [
    'Tuatara are the last survivors of a reptile line older than the dinosaurs.',
    '{name} has a third “eye” on its forehead that senses light.',
    'Tuatara grow so slowly they keep growing for 60 years — some live past 100.',
  ],
  stick: [
    'Stick insects are masters of disguise — some look exactly like leaves or twigs.',
    '{name} can regenerate lost legs as it grows.',
    'Some stick insects reproduce without males at all, cloning whole populations.',
  ],
  cockroach: [
    'Cockroaches have scuttled the Earth for over 300 million years.',
    '{name} can sprint three body-lengths per second and squeeze through cracks a coin thick.',
    'Cockroaches are important recyclers in forests, cleaning up dead leaves and wood.',
  ],
  mayfly: [
    'Mayflies are the only insects with two adult winged stages.',
    '{name} spends years as a stream nymph — then flies for a single day to mate.',
    'Millions of mayflies emerge at once, feeding fish, birds and bats for weeks.',
  ],
  caddis: [
    'Caddisfly larvae are underwater builders that cement their own portable houses.',
    '{name} builds a case from sand grains, twigs or snail shells, like a living backpack.',
    'Anglers copy caddisflies with artificial flies — trout can’t resist them.',
  ],
  earwig: [
    'Earwigs are among the few insects that care for their young.',
    '{name} uses its pincers to fold and guard its eggs, licking them clean.',
    'The “earwig” name is slander — they neither seek nor enter ears.',
  ],
  silverfish: [
    'Silverfish are wingless insects older than the dinosaurs.',
    '{name} dines on book glue, wallpaper paste and sugar — a librarian’s nemesis.',
    'A silverfish can live three years and molt for its entire life.',
  ],
  parasiteisopod: [
    'Parasitic isopods are crustaceans that live on — and in — fish.',
    '{name} replaces a host’s body part with itself, then feeds for life.',
    'Despite the horror show, parasitic isopods rarely kill their hosts.',
  ],
  cycad: [
    'Cycads are living fossils that fed the dinosaurs.',
    '{name} grows one crown of tough fronds and cones instead of flowers.',
    'Some cycads live over 1,000 years, growing a few millimetres a decade.',
  ],
  gnetophyte: [
    'Gnetophytes are the weird cousins of conifers, with wood like trees and vessels like flowers.',
    '{name} survives where rain almost never falls, drinking fog through wide leaves.',
    'Gnetophytes may hold clues to how flowering plants first evolved.',
  ],
  treedisease: [
    'Tree disease fungi travel the world in timber, bark beetles and nursery pots.',
    '{name} kills trees by choking their water channels.',
    'Epidemics like these reshaped whole continents’ forests — elms, chestnuts and ashes.',
  ],
  bordetella: [
    'Bordetella bacteria colonize the windpipe, where cilia normally sweep lungs clean.',
    '{name} paralyzes that broom of cilia, causing coughing fits that last months.',
    'Vaccines turned this “hundred-day cough” from a childhood killer into a rarity.',
  ],
}

/* Size + lifespan profiles per fact key. Aliased below. */
const P = {
  bigcat: ['1.5–3.1 m nose to tail', '10–15 years in the wild'],
  smallcat: ['40 cm – 1 m long', '8–16 years'],
  canid: ['45 cm – 1.6 m long', '6–14 years in the wild'],
  bear: ['1.2–2.8 m long', '20–35 years'],
  panda: ['1.2–1.9 m long', '15–20 years in the wild'],
  mustelid: ['20 cm – 1.2 m long', '5–10 years'],
  skunk: ['40–80 cm long', '2–4 years in the wild'],
  pinniped: ['1.5–6 m long', '15–40 years'],
  whale: ['6–33 m long', '40–200 years'],
  spermwhale: ['11–20 m long', 'Up to 70 years'],
  monodont: ['3.5–5.5 m long', '30–50 years'],
  dolphin: ['1.5–9 m long', '20–60 years'],
  riverdolphin: ['1.5–2.5 m long', '10–30 years'],
  ape: ['1–1.8 m tall', '35–60 years'],
  monkey: ['30 cm – 1 m tall', '15–45 years'],
  lemur: ['25–70 cm plus tail', '15–30 years'],
  tarsier: ['10–15 cm plus tail', '12–20 years'],
  elephant: ['Up to 4 m at the shoulder', '60–70 years'],
  afrotheria: ['30 cm – 2 m long', '8–25 years'],
  bovid: ['70 cm – 2 m at the shoulder', '10–25 years'],
  deer: ['70 cm – 1.5 m at the shoulder', '8–20 years'],
  giraffe: ['Up to 5.5 m tall', '20–25 years'],
  camelid: ['1.5–3 m at the shoulder', '15–50 years'],
  pig: ['50 cm – 1.2 m at the shoulder', '8–15 years'],
  hippo: ['Up to 1.6 m at the shoulder', '40–50 years'],
  equid: ['1.1–1.6 m at the shoulder', '25–40 years'],
  rhino: ['Up to 1.9 m at the shoulder', '35–50 years'],
  tapir: ['1.8–2.5 m long', '25–30 years'],
  squirrel: ['20–70 cm with tail', '3–12 years'],
  rodent: ['5–35 cm long', '1–8 years'],
  beaver: ['75 cm – 1.2 m with tail', '10–20 years'],
  spiky: ['15 cm – 1 m long', '3–20 years'],
  kangaroo: ['60 cm – 1.8 m tall', '6–23 years'],
  koala: ['60–85 cm long', '10–15 years'],
  wombat: ['70 cm – 1.2 m long', '5–15 years'],
  marsupial: ['10 cm – 1.3 m long', '2–15 years'],
  dasyurid: ['10–75 cm long', '2–7 years'],
  platypus: ['40–60 cm long', '10–17 years'],
  sloth: ['40–70 cm long', '20–30 years'],
  anteater: ['1–2 m with tail', '14–16 years'],
  armadillo: ['30 cm – 1.5 m long', '7–20 years'],
  pangolin: ['30 cm – 1.4 m long', 'Up to 20 years'],
  shrew: ['3–15 cm long', '1–2 years'],
  mole: ['10–20 cm long', '3–6 years'],
  bat: ['3 cm – 1.7 m wingspan', '5–30 years'],
  raptor: ['25 cm – 1 m tall', '10–40 years'],
  owl: ['13–75 cm tall', '4–25 years'],
  parrot: ['9 cm – 1 m long', '15–80 years'],
  corvid: ['20–70 cm long', '7–20 years'],
  songbird: ['10–70 cm long', '2–20 years'],
  waterfowl: ['30 cm – 1.8 m long', '5–30 years'],
  seabird: ['25 cm – 1.2 m wingspan to 3.5 m', '10–60 years'],
  penguin: ['30 cm – 1.2 m tall', '6–30 years'],
  ratite: ['35 cm – 2.8 m tall', '10–70 years'],
  hummingbird: ['5–23 cm long', '3–12 years'],
  kingfisher: ['10–45 cm long', '5–15 years'],
  hornbill: ['40 cm – 1.2 m long', '15–50 years'],
  toucan: ['30–65 cm long', '12–20 years'],
  woodpecker: ['8–55 cm long', '4–15 years'],
  cuckoo: ['15–65 cm long', '5–12 years'],
  dove: ['15–75 cm long', '3–15 years'],
  gamebird: ['15 cm – 1.3 m long', '2–25 years'],
  flamingo: ['80 cm – 1.5 m tall', '20–40 years'],
  wading: ['25 cm – 1.5 m tall', '10–35 years'],
  puffin: ['25–40 cm tall', '20–30 years'],
  swift: ['9–25 cm long', '5–20 years'],
  shark: ['20 cm – 6 m long', '12–70 years'],
  ray: ['30 cm – 7 m wide', '15–50 years'],
  fish: ['5 cm – 4.5 m long', '1–40 years'],
  scombrid: ['30 cm – 4.5 m long', '5–40 years'],
  cichlid: ['3–90 cm long', '2–15 years'],
  clownfish: ['7–15 cm long', '6–10 years'],
  herring: ['15–40 cm long', '5–20 years'],
  salmon: ['50 cm – 1.5 m long', '2–8 years'],
  characin: ['2 cm – 1 m long', '2–10 years'],
  eel: ['30 cm – 4 m long', '5–85 years'],
  coelacanth: ['1.5–2 m long', 'Up to 60 years'],
  sturgeon: ['1–6 m long', '50–100 years'],
  seahorse: ['1.5–35 cm tall', '1–5 years'],
  puffer: ['2.5 cm – 1.2 m long', '4–10 years'],
  deepsea: ['5 cm – 1.5 m long', '1–30 years'],
  hagfish: ['40 cm – 1.3 m long', 'Up to 40 years'],
  lamprey: ['15 cm – 1.2 m long', '1–8 years'],
  frog: ['1–35 cm long', '1–15 years'],
  dartfrog: ['1.5–6 cm long', '3–15 years'],
  salamander: ['5 cm – 1.8 m long', '5–30 years'],
  axolotl: ['15–45 cm long', '10–15 years'],
  lizard: ['2 cm – 3 m long', '1–30 years'],
  gecko: ['1.5–35 cm long', '5–20 years'],
  snake: ['10 cm – 9 m long', '5–30 years'],
  croc: ['1.5–7 m long', '30–70 years'],
  turtle: ['20 cm – 2.5 m shell', '20–100 years'],
  tortoise: ['15 cm – 1.3 m shell', '50–190 years'],
  beetle: ['0.2–17 cm long', '2 months – 3 years'],
  firefly: ['5–25 mm long', '1–2 months as an adult'],
  butterfly: ['2–30 cm wingspan', '2 weeks – 1 year'],
  moth: ['1–30 cm wingspan', '1 week – 1 year'],
  bee: ['2 mm – 4 cm long', '5 weeks – 5 years (queens)'],
  wasp: ['2 mm – 5 cm long', 'A few weeks – 1 year'],
  ant: ['0.7 mm – 5 cm long', 'Weeks – 30 years (queens)'],
  hopper: ['1–13 cm long', 'A few months – 1 year'],
  mantis: ['1–18 cm long', '6 months – 1 year'],
  dragonfly: ['2.5–19 cm wingspan to 19 cm', '6 months – 6 years (larvae)'],
  truebug: ['1 mm – 12 cm long', 'Weeks – 17 years (cicadas)'],
  cicada: ['2–7 cm long', '2–17 years'],
  fly: ['1 mm – 7 cm long', 'Days – months'],
  mosquito: ['3–10 mm long', 'Weeks – months'],
  spider: ['0.5 mm – 30 cm leg span', '1–30 years (tarantulas)'],
  scorpion: ['1–23 cm long', '3–15 years'],
  tick: ['1 mm – 3 cm engorged', 'Months – years'],
  crab: ['5 mm – 4 m leg span', '1–100 years'],
  shrimp: ['1–40 cm long', '1–20 years'],
  mantisshrimp: ['3–38 cm long', 'Up to 20 years'],
  krill: ['1–6 cm long', '2–6 years'],
  isopod: ['1 mm – 50 cm long', '1–5 years'],
  barnacle: ['1 mm – 8 cm wide', '1–20 years'],
  snail: ['2 mm – 90 cm long', '1–25 years'],
  cone: ['1–23 cm shell', '5–10 years'],
  nudibranch: ['1–60 cm long', 'Weeks – 1 year'],
  bivalve: ['2 mm – 1.4 m wide', '2–500 years'],
  octopus: ['2 cm – 9 m arm span', '6 months – 5 years'],
  squid: ['1 cm – 13 m long', '1–5 years'],
  nautilus: ['15–25 cm shell', '15–20 years'],
  starfish: ['1 cm – 1 m across', '5–35 years'],
  urchin: ['1–35 cm across', '4–200 years'],
  jellyfish: ['1 mm – 2.5 m across', 'Hours – a few years'],
  coral: ['Millimetres – metres per colony', 'Years – millennia (reefs)'],
  sponge: ['1 mm – 3 m tall', 'Months – 10,000 years'],
  earthworm: ['1 mm – 3 m long', '1–8 years'],
  flatworm: ['1 mm – 60 cm long', 'Days – years'],
  roundworm: ['0.3 mm – 8 m long', 'Days – years'],
  tardigrade: ['0.1–1.5 mm long', 'Up to 30 years in a tun'],
  combjelly: ['1 mm – 1.5 m long', 'Weeks – months'],
  tunicate: ['1 mm – 30 cm long', 'Days – years'],
  myriapod: ['2 mm – 38 cm long', '1–10 years'],
  hominin: ['1.2–1.8 m tall', 'Roughly 30–70 years'],
  lagomorph: ['20–70 cm long', '1–12 years'],
  tree: ['5–110 m tall', '50–5,000 years'],
  conifer: ['1–115 m tall', '50–5,000 years'],
  ginkgo: ['10–40 m tall', 'Over 1,000 years'],
  yew: ['1–20 m tall', 'Up to 3,000 years'],
  fern: ['5 cm – 20 m tall', 'Years – centuries'],
  horsetail: ['10 cm – 8 m tall', 'Perennial, years'],
  moss: ['1–60 cm across', 'Years per patch'],
  grass: ['5 cm – 30 m (bamboo) tall', 'Annual or perennial'],
  bamboo: ['1–30 m tall', 'Perennial, decades'],
  succulent: ['1 cm – 18 m tall', '5–100 years'],
  cactus: ['1 cm – 20 m tall', '10–200 years'],
  aloe: ['10 cm – 18 m tall', '10–100 years'],
  carnivorous: ['1 cm – 1.5 m tall', '1–20 years'],
  orchid: ['2 cm – 20 m (vines) tall', 'Years – decades'],
  flower: ['5 cm – 3 m tall', 'Annual or perennial'],
  nightshade: ['20 cm – 3 m tall', 'Annual or perennial'],
  gourd: ['Vines to 10 m long', 'One season'],
  herb: ['10 cm – 2 m tall', 'Annual or perennial'],
  fruittree: ['2–30 m tall', '10–100 years'],
  banana: ['2–9 m tall', 'Perennial, one fruiting per stem'],
  coffee: ['2–10 m tall', '20–100 years'],
  tea: ['1–15 m tall', '50–100 years'],
  palm: ['1–60 m tall', '20–100 years'],
  waterlily: ['Leaves 5 cm – 3 m wide', 'Perennial, years'],
  duckweed: ['1–10 mm fronds', 'Weeks per plant'],
  mangrove: ['1–30 m tall', 'Decades – centuries'],
  mushroom: ['1–40 cm cap', 'Days – weeks above ground'],
  bolete: ['3–30 cm cap', 'Days – weeks above ground'],
  waxcap: ['1–10 cm cap', 'Days – weeks above ground'],
  glowmushroom: ['1–10 cm cap', 'Days – weeks above ground'],
  inkcap: ['2–20 cm cap', 'Hours – days above ground'],
  coralfungus: ['2–30 cm tall', 'Weeks above ground'],
  bracket: ['5 cm – 1 m wide', 'Years – decades'],
  puffball: ['1 cm – 1.5 m across', 'Days – weeks above ground'],
  stinkhorn: ['5–30 cm tall', 'Days above ground'],
  birdsnest: ['5–15 mm cups', 'Days – weeks above ground'],
  morel: ['2–30 cm tall', 'Days – weeks above ground'],
  truffle: ['1–10 cm wide', 'Weeks – months underground'],
  mold: ['Threads millimetres to metres', 'Days – weeks per colony'],
  breadmold: ['Threads centimetres long', 'Days per colony'],
  candida: ['3–15 micrometres per cell', 'Divides every few hours'],
  malassezia: ['2–7 micrometres per cell', 'Divides every few days'],
  cryptococcus: ['4–20 micrometres per cell', 'Divides every few hours'],
  myco: ['1–10 micrometres per cell', 'Divides every 20 hours (slow!)'],
  chytrid: ['5–100 micrometres per cell', 'Days per generation'],
  mycorrhiza: ['Threads metres – kilometres', 'Years – centuries'],
  rust: ['Millimetre pustules', 'Days – weeks per cycle'],
  smut: ['Millimetre galls', 'Days – weeks per cycle'],
  ergot: ['Millimetre grains', 'Weeks per cycle'],
  cordyceps: ['1–30 cm stalks', 'Weeks per fruiting body'],
  entomopathogen: ['Millimetre – centimetre stalks', 'Weeks per fruiting body'],
  microsporidia: ['1–40 micrometres per spore', 'Days per cycle'],
  yeast: ['3–40 micrometres per cell', 'Divides every 1–3 hours'],
  lichen: ['1 cm – 1 m across', 'Years – thousands of years'],
  armillaria: ['Up to kilometres of mycelium', 'Hundreds – thousands of years'],
  jelly: ['1–8 cm blobs', 'Days – weeks above ground'],
  schizo: ['3–25 micrometres per cell', 'Divides every 2–4 hours'],
  coronavirus: ['80–220 nanometres', 'Hours to days outside a host'],
  flu: ['80–120 nanometres', 'Up to 48 hours on surfaces'],
  paramyxo: ['150–300 nanometres', 'Hours outside a host'],
  filo: ['800 nm – 14 micrometres long', 'Hours outside a host'],
  rhabdo: ['75 × 180 nanometres', 'Hours outside a host'],
  flavi: ['40–60 nanometres', 'Hours outside a host'],
  picorna: ['27–30 nanometres', 'Days outside a host'],
  calici: ['27–40 nanometres', 'Weeks on surfaces'],
  reo: ['60–85 nanometres', 'Months in water'],
  herpes: ['150–200 nanometres', 'Hours outside a host'],
  pox: ['200 × 300 nanometres', 'Months to years in dried scabs'],
  adeno: ['70–90 nanometres', 'Weeks on surfaces'],
  papilloma: ['52–55 nanometres', 'Days to months on surfaces'],
  parvo: ['18–26 nanometres', 'Months in the environment'],
  hepadna: ['42 nanometres', 'Days outside a host'],
  retro: ['80–120 nanometres', 'Minutes to hours outside the body'],
  bunya: ['80–120 nanometres', 'Hours in dry air'],
  arena: ['50–300 nanometres', 'Days in rodent droppings'],
  phage: ['20–200 nanometres', 'Years in the right conditions'],
  giantvirus: ['200–750 nanometres', 'Indefinite as dormant particles'],
  plantvirus: ['17–300 nanometres', 'Years in dried plant material'],
  viroid: ['A few hundred bases of RNA', 'Years in dried plant material'],
  halophile: ['0.5–5 micrometres per cell', 'Possibly thousands of years in salt'],
  methanogen: ['0.5–3 micrometres per cell', 'Colonies persist for a lifetime'],
  hyperthermo: ['0.5–3 micrometres per cell', 'Divides in under an hour'],
  thermophile: ['0.5–5 micrometres per cell', 'Divides in 1–2 hours'],
  acidophile: ['0.5–3 micrometres per cell', 'Divides in hours to days'],
  ammoniaox: ['0.5–3 micrometres per cell', 'Divides every few days'],
  asgard: ['0.5–3 micrometres per cell', 'Divides every week or so'],
  nanoarch: ['0.1–0.5 micrometres per cell', 'Divides slowly, riding a host'],
  enteric: ['1–3 micrometres per cell', 'Divides every 20–30 minutes'],
  lacto: ['0.5–5 micrometres per cell', 'Divides every 30–60 minutes'],
  strep: ['0.5–2 micrometres per cell', 'Divides every 20–60 minutes'],
  staph: ['0.5–1.5 micrometres per cell', 'Divides every 30–60 minutes'],
  bacillus: ['1–10 micrometres per cell', 'Spores survive for centuries'],
  clostridium: ['1–10 micrometres per cell', 'Spores survive for centuries'],
  coryne: ['1–5 micrometres per cell', 'Divides every few hours'],
  mycoplasma: ['0.2–0.8 micrometres per cell', 'Divides every 1–16 hours'],
  spirochete: ['5–250 micrometres long', 'Divides every 6–16 hours'],
  vibrio: ['1–3 micrometres per cell', 'Divides every 15–30 minutes'],
  campylobacter: ['0.5–5 micrometres long', 'Divides every 2–3 hours'],
  pseudomonad: ['1–5 micrometres per cell', 'Divides every 1–2 hours'],
  legionella: ['1–2 micrometres per cell', 'Divides slowly inside amoebae'],
  rhizobium: ['1–3 micrometres per cell', 'Divides for years inside root nodules'],
  nitrifier: ['0.5–3 micrometres per cell', 'Divides every 7–24 hours'],
  sulfur: ['0.5–10 micrometres per cell', 'Divides every few hours'],
  cyano: ['0.5–60 micrometres per cell', 'Colonies live for decades'],
  phototroph: ['0.5–10 micrometres per cell', 'Divides every few hours'],
  myxococcus: ['3–8 micrometres per cell', 'Divides every 4–8 hours'],
  bdellovibrio: ['0.2–0.5 × 0.5–2.5 micrometres', 'Divides every 3–4 hours inside prey'],
  rickettsia: ['0.3–2 micrometres per cell', 'Lives only inside host cells'],
  chlamydia: ['0.2–1.5 micrometres per cell', 'Lives only inside host cells'],
  streptomyces: ['Filaments millimetres long', 'Colonies persist for years in soil'],
  gutmicrobe: ['0.5–5 micrometres per cell', 'Divides every 20 minutes – hours'],
  micrococcus: ['0.5–3.5 micrometres per cell', 'Divides every 1–2 hours'],
  neisseria: ['0.6–1 micrometre per cell', 'Divides every 1–3 hours'],
  plancto: ['1–2 micrometres per cell', 'Divides every 10–30 hours'],
  verruco: ['0.5–2 micrometres per cell', 'Divides every 10–30 hours'],
  chloroflexus: ['Filaments 1–5 micrometres wide', 'Colonies persist for years'],
  amoeba: ['0.1 mm – 5 mm across', 'Days to weeks per generation'],
  entamoeba: ['10–60 micrometres', 'Cysts survive weeks outside a host'],
  ciliate: ['10 micrometres – 4 mm', 'Divides every few hours to days'],
  kinetoplastid: ['5–100 micrometres', 'Divides every 6–24 hours'],
  apicomplexan: ['1–15 micrometres', 'Lives inside host cells'],
  schizo: ['3–25 micrometres per cell', 'Divides every 2–4 hours'],
  dino: ['5 micrometres – 2 mm', 'Divides every 1–3 days'],
  diatom: ['2 micrometres – 2 mm', 'Divides every 1–7 days'],
  goldenalga: ['2–50 micrometres', 'Divides every 1–3 days'],
  brownalga: ['1 mm – 60 m long', 'Months to years'],
  kelp: ['Up to 60 m long', 'Up to 8 years per frond'],
  redalga: ['1 mm – 2 m long', 'Months to years'],
  greenalga: ['1 micrometre – 1 m', 'Days to months'],
  charophyte: ['1 cm – 1 m long', 'Perennial, months to years'],
  euglenid: ['10–500 micrometres', 'Divides every 1–2 days'],
  slimemold: ['1 mm – 30 cm plasmodium', 'Days to weeks per plasmodium'],
  watermold: ['Threads millimetres – metres', 'Days per colony'],
  foram: ['0.1 mm – 20 cm shell', 'Weeks to years'],
  radiolaria: ['0.1–2 mm across', 'Days to weeks'],
  heliozoan: ['20 micrometres – 1 mm', 'Days per generation'],
  testate: ['10–300 micrometres', 'Days per generation'],
  choano: ['3–10 micrometres', 'Divides every 6–24 hours'],
  protistmisc: ['Micrometres to millimetres', 'Days per generation'],
  gibbon: ['45–90 cm tall, arms longer than legs', '25–40 years'],
  sirenian: ['2.5–4 m long', '40–70 years'],
  vulture: ['60–110 cm long, wingspan up to 3 m', '20–50 years'],
  molerat: ['8–35 cm long', '10–30 years (queens longer)'],
  tuatara: ['Up to 80 cm long', '60–100+ years'],
  stick: ['5–30 cm long', '1–3 years'],
  cockroach: ['1–8 cm long', '1–2 years'],
  mayfly: ['1–3 cm long', 'Nymph for 1–3 years, adult for one day'],
  caddis: ['1–2.5 cm long', 'Larva for months, adult for weeks'],
  earwig: ['1–2.5 cm long', 'About 1 year'],
  silverfish: ['1–2 cm long', '2–8 years'],
  parasiteisopod: ['0.5–4 cm long', '1–3 years'],
  cycad: ['1–10 m tall', 'Up to 1,000 years'],
  gnetophyte: ['Two leaves, spreading metres wide', 'Up to 2,000 years'],
  treedisease: ['Microscopic threads in wood', 'Spreads for decades in a forest'],
  bordetella: ['0.2–0.5 micrometres per cell', 'Weeks to months in a host'],
}

export const PROFILE = { ...P }

/* Fact-bank aliases: minor keys reuse a related bank. */
const FA = {
  afrotheria: F.elephant, anteater: F.sloth, pangolin: F.spiky, armadillo: F.spiky,
  koala: F.marsupial, wombat: F.marsupial, dasyurid: F.marsupial,
  dove: F.songbird, swift: F.hummingbird,
  cuckoo: F.songbird, gamebird: F.waterfowl, flamingo: F.wading, puffin: F.seabird,
  hornbill: F.toucan, woodpecker: F.toucan,
  monodont: F.dolphin, riverdolphin: F.dolphin, spermwhale: F.whale,
  smallcat: F.bigcat, panda: F.bear, skunk: F.mustelid,
  lagomorph: F.rodent, jerboa: F.rodent, chinchilla: F.rodent,
  tortoise: F.turtle, gecko: F.lizard, dartfrog: F.frog, axolotl: F.salamander,
  moth: F.butterfly, mosquito: F.fly, wasp: F.bee, cicada: F.truebug,
  krill: F.crusty, isopod: F.crusty, barnacle: F.crusty,
  cone: F.snail, nudibranch: F.snail,
  squid: F.octopus, nautilus: F.squid,
  urchin: F.starfish, combjelly: F.jellyfish, tunicate: F.sponge,
  myriapod: F.earthworm, flatworm: F.earthworm, roundworm: F.earthworm,
  bolete: F.mushroom, waxcap: F.mushroom, glowmushroom: F.mushroom, inkcap: F.mushroom,
  coralfungus: F.mushroom, bracket: F.mushroom, puffball: F.mushroom, stinkhorn: F.mushroom,
  birdsnest: F.puffball, morel: F.mushroom,
  breadmold: F.mold, candida: F.yeast, malassezia: F.yeast, cryptococcus: F.yeast,
  chytrid: F.mold, rust: F.smut, ergot: F.smut,
  entomopathogen: F.cordyceps, microsporidia: F.mold,
  conifer: F.tree, ginkgo: F.tree, yew: F.conifer, horsetail: F.fern,
  succulent: F.cactus, aloe: F.succulent, orchid: F.flower, nightshade: F.herb,
  gourd: F.fruittree, banana: F.fruittree, coffee: F.fruittree, tea: F.fruittree,
  palm: F.tree, waterlily: F.duckweed, mangrove: F.tree, carnivorous: F.flower,
  charophyte: F.greenalga, goldenalga: F.diatom, heliozoan: F.testate,
  entamoeba: F.amoeba, schizo: F.yeast, kinetoplastid: F.euglenid,
  watermold: F.brownalga, apicomplexan: F.kinetoplastid,
  thermophile: F.hyperthermo, sulfur: F.acidophile, ammoniaox: F.nitrifier,
  legionella: F.rickettsia, chlamydia: F.rickettsia, campylobacter: F.vibrio,
  gutmicrobe: F.enteric, micrococcus: F.staph,
}

for (const [k, v] of Object.entries(FA)) F[k] = v

export const FACT_BANKS = F
