// GrinKingdom seed rows — archaea.

export const ARCHAEA_ROWS = [
  ['methanogen-rod', 'Methanobrevibacter smithii', 'Methanobrevibacter smithii', '🫧', 'The most common archaeon in your gut — it turns hydrogen into methane.'],
  ['methanogen-rod', 'Methanobacterium formicicum', 'Methanobacterium formicicum', '🫧', 'A rod-shaped methane maker from wetlands and animal guts.'],
  ['methanogen-cocci', 'Methanococcus jannaschii', 'Methanococcus jannaschii', '🫧', 'The first archaeon ever to have its whole genome read.'],
  ['methanogen-cocci', 'Methanocaldococcus jannaschii', 'Methanocaldococcus jannaschii', '🌋', 'A methane-maker that lives at deep-sea vent temperatures.'],
  ['methanogen-sarcina', 'Methanosarcina barkeri', 'Methanosarcina barkeri', '🫧', 'A cube-shaped methane-maker that can also eat acetate.'],
  ['methanogen-sarcina', 'Methanosarcina acetivorans', 'Methanosarcina acetivorans', '🫧', 'A methane microbe with one of the largest archaeal genomes.'],
  ['methanogen-thermo', 'Methanopyrus kandleri', 'Methanopyrus kandleri', '🌋', 'A methane-maker that holds the heat record for life — 122 °C.'],
  ['methanogen-thermo', 'Methanothermus fervidus', 'Methanothermus fervidus', '🌋', 'A methane-maker from boiling Icelandic springs.'],
  ['halophile', 'Halobacterium salinarum', 'Halobacterium salinarum', '🧂', 'The microbe that turns salt ponds watermelon-pink.'],
  ['halophile', 'Haloferax volcanii', 'Haloferax volcanii', '🧂', 'A Dead Sea native that scientists use to study archaeal genetics.'],
  ['halophile-square', 'Haloquadratum walsbyi', 'Haloquadratum walsbyi', '🧂', 'Square cells so thin they float like microbial postage stamps.'],
  ['halophile-square', 'Halorubrum sodomense', 'Halorubrum sodomense', '🧂', 'A square-ish salt lover from the Dead Sea\'s pinkest pools.'],
  ['halophile-cocci', 'Halococcus morrhuae', 'Halococcus morrhuae', '🧂', 'A salt-loving coccus that can survive in salted fish.'],
  ['halophile-cocci', 'Natronococcus occultus', 'Natronococcus occultus', '🧂', 'A soda-lake coccus that likes it salty and alkaline.'],
  ['sulfolobus', 'Sulfolobus acidocaldarius', 'Sulfolobus acidocaldarius', '🌋', 'A lobed acid-lover from Yellowstone hot springs.'],
  ['sulfolobus', 'Sulfolobus solfataricus', 'Sulfolobus solfataricus', '🌋', 'An acid-hot-spring archaeon discovered in Italian solfataras.'],
  ['thermoproteus', 'Thermoproteus tenax', 'Thermoproteus tenax', '🌋', 'A branching archaeon from volcanic hot springs.'],
  ['thermoproteus', 'Pyrobaculum aerophilum', 'Pyrobaculum aerophilum', '🌋', 'A rod-shaped heat lover that can grow with or without oxygen.'],
  ['desulfurococcus', 'Desulfurococcus mobilis', 'Desulfurococcus mobilis', '🌋', 'A sulfur-breather from Icelandic hot springs.'],
  ['desulfurococcus', 'Ignicoccus hospitalis', 'Ignicoccus hospitalis', '🌋', 'A sulfur-loving coccus that hosts an even tinier archaeon on its back.'],
  ['pyrococcus', 'Pyrococcus furiosus', 'Pyrococcus furiosus', '🌋', 'The "rushing fireball" — its DNA polymerase powers modern genetics labs.'],
  ['pyrococcus', 'Pyrococcus abyssi', 'Pyrococcus abyssi', '🌋', 'A deep-sea vent archaeon that thrives at 100 °C.'],
  ['thermococcus', 'Thermococcus gammatolerans', 'Thermococcus gammatolerans', '☢️', 'The most radiation-resistant archaeon known — it shrugs off gamma rays.'],
  ['thermococcus', 'Thermococcus kodakarensis', 'Thermococcus kodakarensis', '🌋', 'A speedy heat lover that doubles every 40 minutes at 85 °C.'],
  ['thermoplasma', 'Thermoplasma acidophilum', 'Thermoplasma acidophilum', '🔥', 'A wall-less archaeon that lives in burning coal refuse piles.'],
  ['thermoplasma', 'Thermoplasma volcanium', 'Thermoplasma volcanium', '🔥', 'A tiny acid-thermophile from volcanic soils.'],
  ['picrophilus', 'Picrophilus oshimae', 'Picrophilus oshimae', '🧪', 'The most acid-loving organism known — it grows at pH 0.'],
  ['picrophilus', 'Picrophilus torridus', 'Picrophilus torridus', '🧪', 'A heat-plus-acid extremophile from Japanese solfataras.'],
  ['ferroplasma', 'Ferroplasma acidiphilum', 'Ferroplasma acidiphilum', '⚒️', 'A cell without a wall that eats iron in acid mine drainage.'],
  ['ferroplasma', 'Ferroplasma acidarmanus', 'Ferroplasma acidarmanus', '⚒️', 'A mine-drainage microbe that dissolves pyrite for lunch.'],
  ['thaumarchaeote', 'Nitrosopumilus maritimus', 'Nitrosopumilus maritimus', '🌊', 'The most abundant organism in the ocean — an ammonia-burner.'],
  ['thaumarchaeote', 'Candidatus Nitrosotenuis cloacae', 'Candidatus Nitrosotenuis cloacae', '🌊', 'An ammonia-oxidizer found in wastewater and soil.'],
  ['nitrososphaera', 'Nitrososphaera viennensis', 'Nitrososphaera viennensis', '🪴', 'A soil ammonia-oxidizer first grown from a Vienna garden.'],
  ['nitrososphaera', 'Candidatus Nitrosocosmicus oleophilus', 'Candidatus Nitrosocosmicus oleophilus', '🪴', 'A garden-soil archaeon that helps plants get their nitrogen.'],
  ['asgard', 'Lokiarchaeum ossiferum', 'Lokiarchaeum ossiferum', '🦠', 'An Asgard archaeon named after Loki — a possible ancestor of us all.'],
  ['asgard', 'Candidatus Prometheoarchaeum syntrophicum', 'Candidatus Prometheoarchaeum syntrophicum', '🦠', 'The first Asgard microbe grown in a lab — it grows finger-like tentacles.'],
  ['nanoarchaeon', 'Nanoarchaeum equitans', 'Nanoarchaeum equitans', '🦠', 'One of the smallest genomes on Earth — it can\'t survive without a host.'],
  ['nanoarchaeon', 'Candidatus Nanobsidianus stetteri', 'Candidatus Nanobsidianus stetteri', '🦠', 'A tiny glass-dagger-shaped archaeon from a hot spring.'],
  ['korarchaeon', 'Candidatus Korarchaeum cryptofilum', 'Candidatus Korarchaeum cryptofilum', '🦠', 'An elusive filament archaeon from Yellowstone — "the secret filament".'],
  ['korarchaeon', 'Korarchaeota enrichment culture', 'Candidatus Korarchaeota archaeon', '🦠', 'A mysterious deep branch of the archaeal family tree.'],
]
