// GrinKingdom seed rows — fungi.

export const FUNGI_ROWS = [
  ['mushroom-amanita', 'Death cap', 'Amanita phalloides', '☠️', 'The world\'s deadliest mushroom, disguised as an innocent white cap.'],
  ['mushroom-amanita', 'Caesar\'s mushroom', 'Amanita caesarea', '🍄', 'The emperor\'s favorite — prized since Roman times.'],
  ['mushroom-agaricus', 'Field mushroom', 'Agaricus campestris', '🍄', 'The meadow mushroom that started our love of champignons.'],
  ['mushroom-agaricus', 'Portobello', 'Agaricus bisporus', '🍄', 'The supermarket mushroom — baby, button, cremini or portobello.'],
  ['mushroom-boletus', 'Penny bun', 'Boletus edulis', '🍄', 'The "king bolete" — the most prized wild mushroom in Europe.'],
  ['mushroom-boletus', 'Devil\'s bolete', 'Rubroboletus satanas', '🍄', 'A blood-red bolete with a devilish reputation.'],
  ['mushroom-russula', 'Charcoal burner', 'Russula cyanoxantha', '🍄', 'A friendly woodland russula with a rainbow of cap colors.'],
  ['mushroom-russula', 'The sickener', 'Russula emetica', '🤢', 'A scarlet woodland mushroom that lives up to its name.'],
  ['mushroom-chanterelle', 'Golden chanterelle', 'Cantharellus cibarius', '🍄', 'The apricot-scented golden treasure of summer forests.'],
  ['mushroom-chanterelle', 'Black trumpet', 'Craterellus cornucopioides', '🎺', 'The "horn of plenty" — a black, smoky-flavored delicacy.'],
  ['mushroom-hericium', 'Lion\'s mane', 'Hericium erinaceus', '🦁', 'A shaggy white pom-pom that may help nerves regrow.'],
  ['mushroom-hericium', 'Bear\'s head tooth', 'Hericium americanum', '🦁', 'A cascading white cascade of icicle teeth.'],
  ['mushroom-grifola', 'Hen of the woods', 'Grifola frondosa', '🐔', 'The maitake — a frilly shelf cluster at the foot of oaks.'],
  ['mushroom-grifola', 'Chicken of the woods', 'Laetiporus sulphureus', '🐔', 'A blazing orange shelf that tastes remarkably like chicken.'],
  ['mushroom-pleurotus', 'Oyster mushroom', 'Pleurotus ostreatus', '🍄', 'The shelf mushroom that grows on trees — and eats nematodes.'],
  ['mushroom-pleurotus', 'King oyster', 'Pleurotus eryngii', '🍄', 'The meaty, thick-stemmed gourmet of stir-fries.'],
  ['mushroom-omphalotus', 'Jack-o\'-lantern', 'Omphalotus olearius', '🎃', 'A glowing orange mushroom that tricks hunters into picking it.'],
  ['mushroom-omphalotus', 'Ghost fungus', 'Omphalotus nidiformis', '👻', 'An Australian mushroom that glows green in the dark.'],
  ['mushroom-marasmius', 'Fairy ring champignon', 'Marasmius oreades', '🧚', 'The mushroom that draws perfect circles in lawns.'],
  ['mushroom-marasmius', 'Horsehair parachute', 'Marasmius rotula', '🧚', 'A tiny mushroom that dries up and revives with the rain.'],
  ['mushroom-mycena', 'Pixie\'s parasol', 'Mycena interrupta', '🧚', 'A cyan-blue pinhead mushroom of Australia\'s forests.'],
  ['mushroom-mycena', 'Bleeding fairy helmet', 'Mycena haematopus', '🩸', 'A mushroom that oozes blood-red latex when snapped.'],
  ['mushroom-coprinus', 'Shaggy ink cap', 'Coprinus comatus', '🖋️', 'The lawyer\'s wig that melts into ink by afternoon.'],
  ['mushroom-coprinus', 'Mica cap', 'Coprinellus micaceus', '🖋️', 'A glittering ink cap that sparkles with mica-like flecks.'],
  ['mushroom-stropharia', 'Wine cap', 'Stropharia rugosoannulata', '🍷', 'A garden giant that grows happily in wood chips.'],
  ['mushroom-stropharia', 'Blue roundhead', 'Stropharia caerulea', '🍄', 'A blue-green cap of parks and wood-chip beds.'],
  ['mushroom-hygrocybe', 'Scarlet waxcap', 'Hygrocybe coccinea', '🕯️', 'A bright red signal of ancient, healthy meadows.'],
  ['mushroom-hygrocybe', 'Parrot waxcap', 'Gliophorus psittacinus', '🦜', 'The slimy waxcap that glows green and yellow.'],
  ['mushroom-armillaria', 'Honey fungus', 'Armillaria mellea', '🍯', 'The tree-killing fungus whose underground web can span kilometres.'],
  ['mushroom-armillaria', 'Humongous fungus', 'Armillaria ostoyae', '🍯', 'The largest living organism on Earth — one web, 2,400 years old.'],
  ['mushroom-lepiota', 'Parasol mushroom', 'Macrolepiota procera', '☂️', 'The drumstick mushroom that towers over lawns.'],
  ['mushroom-lepiota', 'False parasol', 'Chlorophyllum molybdites', '🤢', 'The "vomiter" — North America\'s most-eaten poisonous mushroom.'],
  ['mushroom-lactarius', 'Saffron milk cap', 'Lactarius deliciosus', '🍄', 'The orange mushroom that bleeds carrot-colored milk.'],
  ['mushroom-lactarius', 'Candy cap', 'Lactarius rubidus', '🍬', 'The mushroom that smells exactly like maple syrup.'],
  ['mushroom-morchella', 'Common morel', 'Morchella esculenta', '🍯', 'The honeycomb spring mushroom that foragers dream about.'],
  ['mushroom-morchella', 'Black morel', 'Morchella elata', '🍯', 'A dark-honeycomb delicacy of burnt forests.'],
  ['mushroom-helvella', 'Elfin saddle', 'Helvella lacunosa', '🧝', 'A grey-saddled oddity of woodlands.'],
  ['mushroom-helvella', 'Fluted black elfin saddle', 'Helvella crispa', '🧝', 'A pale saddle mushroom with a fluted stem.'],
  ['mushroom-gyromitra', 'False morel', 'Gyromitra esculenta', '⚠️', 'A brainy brown morel lookalike that can be deadly.'],
  ['mushroom-gyromitra', 'Snowbank false morel', 'Gyromitra gigas', '⚠️', 'A giant spring mushroom that grows at melting snowbanks.'],
  ['bracket', 'Birch polypore', 'Fomitopsis betulina', '🪵', 'The razor-strop fungus that Ötzi the Iceman carried.'],
  ['bracket', 'Turkey tail', 'Trametes versicolor', '🪵', 'The striped bracket with immune-boosting fame.'],
  ['bracket-ganoderma', 'Reishi', 'Ganoderma lucidum', '🪵', 'The glossy "mushroom of immortality" of East Asia.'],
  ['bracket-ganoderma', 'Artist\'s conk', 'Ganoderma applanatum', '🪵', 'A bracket you can draw on — the white underside keeps the sketch.'],
  ['bracket-fomitopsis', 'Red-belted conk', 'Fomitopsis pinicola', '🪵', 'The tough bracket that bleeds amber resin.'],
  ['bracket-fomitopsis', 'Quinine conk', 'Laricifomes officinalis', '🪵', 'A bitter bracket once used as medicine by lumberjacks.'],
  ['bracket-hymenochaete', 'Cinnamon bracket', 'Hymenochaete rubiginosa', '🪵', 'A rusty bracket that clings to dead oak.'],
  ['bracket-hymenochaete', 'Willow bracket', 'Phellinus igniarius', '🪵', 'The hoof-shaped "false tinder fungus" of willows.'],
  ['jelly', 'Wood ear', 'Auricularia auricula-judae', '👂', 'The rubbery ear-shaped fungus of hot-and-sour soup.'],
  ['jelly', 'Witches\' butter', 'Tremella mesenterica', '🧈', 'A wobbly yellow jelly that appears after rain.'],
  ['coral', 'Crown-tipped coral', 'Artomyces pyxidatus', '🪸', 'A fairy-castle coral of dead logs.'],
  ['coral', 'Yellow-tipped coral', 'Ramaria formosa', '🪸', 'A pink-and-gold coral of conifer woods.'],
  ['puffball', 'Giant puffball', 'Calvatia gigantea', '⚪', 'The beach-ball mushroom that can hold trillions of spores.'],
  ['puffball', 'Common puffball', 'Lycoperdon perlatum', '⚪', 'The gem-studded puffball that puffs when poked.'],
  ['stinkhorn', 'Common stinkhorn', 'Phallus impudicus', '🤢', 'A foul-smelling spike that erupts overnight.'],
  ['stinkhorn', 'Devil\'s fingers', 'Clathrus archeri', '👹', 'A red tentacled alien egg that smells of rot.'],
  ['earthstar', 'Barometer earthstar', 'Astraeus hygrometricus', '⭐', 'The star mushroom that opens and closes with the weather.'],
  ['earthstar', 'Collared earthstar', 'Geastrum triplex', '⭐', 'A puffball that peels open into a star on a saucer.'],
  ['birdsnest', 'Common bird\'s nest', 'Crucibulum laeve', '🪺', 'A cup of tiny eggs that splashes spores out in rain.'],
  ['birdsnest', 'Fluted bird\'s nest', 'Cyathus striatus', '🪺', 'A striped nest whose "eggs" fire out like cannonballs.'],
  ['truffle', 'White truffle', 'Tuber magnatum', '🤍', 'The rarest truffle, worth more than gold by weight.'],
  ['truffle', 'Oregon white truffle', 'Tuber oregonense', '🤍', 'The Pacific Northwest truffle foraged with dogs.'],
  ['mold-asco', 'Green bread mold', 'Penicillium chrysogenum', '🧀', 'The accidental mold that gave the world penicillin.'],
  ['mold-asco', 'Blue cheese mold', 'Penicillium roqueforti', '🧀', 'The mold that veins Roquefort and Stilton blue.'],
  ['mold-asco', 'Camembert mold', 'Penicillium camemberti', '🧀', 'The snowy rind-maker of soft cheeses.'],
  ['mold-mucor', 'Pin mold', 'Mucor mucedo', '📌', 'The pin-capped fuzz on old bread and fruit.'],
  ['mold-mucor', 'Tempeh mold', 'Rhizopus oligosporus', '🫘', 'The mold that ferments soybeans into tempeh.'],
  ['mold-rhizopus', 'Black bread mold', 'Rhizopus stolonifer', '🍞', 'The fast-spreading black fuzz of forgotten bread.'],
  ['mold-rhizopus', 'Mucormycosis mold', 'Rhizopus arrhizus', '🍞', 'A bread mold that can turn dangerous in weakened bodies.'],
  ['mold-hypocreales', 'Trichoderma', 'Trichoderma viride', '🟢', 'A green mold that protects crops — and fights other fungi.'],
  ['mold-hypocreales', 'Golden mold', 'Fusarium graminearum', '🟡', 'A cereal mold whose toxins have shaped history.'],
  ['mold-sordariales', 'Neurospora crassa', 'Neurospora crassa', '🟠', 'The orange bread mold that unlocked how genes make enzymes.'],
  ['mold-sordariales', 'Sordaria fimicola', 'Sordaria fimicola', '🟠', 'The dung mold that genetics classes use to watch crossing-over.'],
  ['mold-leotiomycetes', 'Botrytis cinerea', 'Botrytis cinerea', '🍇', 'The "noble rot" that concentrates sweet wine grapes.'],
  ['mold-leotiomycetes', 'Sclerotinia sclerotiorum', 'Sclerotinia sclerotiorum', '🟤', 'The white mold that rots hundreds of crops.'],
  ['mold-dothideomycetes', 'Apple scab fungus', 'Venturia inaequalis', '🍎', 'The fungus that freckles apple leaves and fruit.'],
  ['mold-dothideomycetes', 'Sooty mold', 'Capnodium citri', '🖤', 'The black coating that grows on insect honeydew.'],
  ['mold-capnodiales', 'Black spot of roses', 'Diplocarpon rosae', '🌹', 'The fungus behind those black circles on rose leaves.'],
  ['mold-capnodiales', 'Sooty blotch', 'Gloeodes pomigena', '🍏', 'A harmless film that smudges apples.'],
  ['yeast', 'Brewer\'s yeast', 'Saccharomyces cerevisiae', '🍺', 'The yeast that built bread, beer and modern biology.'],
  ['yeast', 'Boulardii yeast', 'Saccharomyces cerevisiae var. boulardii', '🍞', 'A probiotic yeast that can calm upset guts.'],
  ['yeast-other', 'Kombucha yeast', 'Brettanomyces bruxellensis', '🍵', 'The wild yeast that gives sour beer its funk.'],
  ['yeast-other', 'Kefir yeast', 'Kluyveromyces marxianus', '🥛', 'A milk-loving yeast from kefir grains.'],
  ['candida', 'Candida albicans', 'Candida albicans', '🦠', 'The yeast that lives in all of us — until it gets ideas.'],
  ['candida', 'Candida auris', 'Candida auris', '🏥', 'The drug-resistant "superbug yeast" that appeared in 2009.'],
  ['cryptococcus', 'Cryptococcus neoformans', 'Cryptococcus neoformans', '🦠', 'A slime-capsuled yeast spread by pigeon droppings.'],
  ['cryptococcus', 'Cryptococcus gattii', 'Cryptococcus gattii', '🌲', 'The tropical tree yeast that can infect healthy lungs.'],
  ['malassezia', 'Malassezia globosa', 'Malassezia globosa', '🦠', 'The scalp yeast behind most dandruff.'],
  ['malassezia', 'Malassezia furfur', 'Malassezia furfur', '🦠', 'A skin yeast that can cause blotchy summer rashes.'],
  ['schizo', 'Fission yeast', 'Schizosaccharomyces pombe', '🧬', 'The rod-shaped yeast that taught us the cell cycle.'],
  ['schizo', 'Pombe\'s cousin', 'Schizosaccharomyces japonicus', '🧬', 'A fission yeast that splits with a twist.'],
  ['rust', 'Wheat stem rust', 'Puccinia graminis', '🟠', 'The rust that has caused famines since ancient Rome.'],
  ['rust', 'Coffee rust', 'Hemileia vastatrix', '☕', 'The orange rust that reshaped the world\'s coffee map.'],
  ['rust', 'Cedar-apple rust', 'Gymnosporangium juniperi-virginianae', '🟠', 'A two-host rust that makes orange jelly on cedars.'],
  ['smut', 'Corn smut', 'Ustilago maydis', '🌽', 'The grey corn gall that Mexico cooks as huitlacoche.'],
  ['smut', 'Loose smut of barley', 'Ustilago nuda', '🌾', 'A smut that turns barley heads to black dust.'],
  ['ergot', 'Ergot of rye', 'Claviceps purpurea', '🟣', 'The grain fungus whose toxins once caused dancing plagues.'],
  ['ergot', 'Ergot of grasses', 'Claviceps paspali', '🟣', 'A pasture ergot that poisons livestock.'],
  ['cordyceps', 'Caterpillar fungus', 'Ophiocordyceps sinensis', '🐛', 'The zombie fungus harvested in the Himalayas as medicine.'],
  ['cordyceps', 'Zombie-ant fungus', 'Ophiocordyceps unilateralis', '🐜', 'The fungus that steers ants to die on the perfect leaf.'],
  ['entomopathogen', 'Fly death fungus', 'Entomophthora muscae', '🪰', 'The fungus that glues flies to windows before sprouting.'],
  ['entomopathogen', 'Green muscardine', 'Metarhizium anisopliae', '🟢', 'The green killer used as a natural insecticide.'],
  ['chytrid', 'Frog-killer chytrid', 'Batrachochytrium dendrobatidis', '🐸', 'The chytrid that has pushed dozens of frog species extinct.'],
  ['chytrid', 'Salamander chytrid', 'Batrachochytrium salamandrivorans', '🦎', 'The newest amphibian plague, spreading through Europe.'],
  ['chytrid-sapro', 'Allomyces', 'Allomyces macrogynus', '🦠', 'A water chytrid that grows tiny branching trees on seeds.'],
  ['chytrid-sapro', 'Spizellomyces punctatus', 'Spizellomyces punctatus', '🦠', 'A soil chytrid with swimming spores — a living fossil of fungi.'],
  ['blastocladiella', 'Blastocladiella emersonii', 'Blastocladiella emersonii', '🦠', 'A water fungus with a motile zoospore that swims like an animal.'],
  ['blastocladiella', 'Coelomomyces', 'Coelomomyces psorophorae', '🦟', 'A mosquito-killing water fungus with a two-host life cycle.'],
  ['mycorrhizal-glomus', 'Glomus mosseae', 'Funneliformis mosseae', '🕸️', 'A root-web fungus that feeds most land plants.'],
  ['mycorrhizal-glomus', 'Glomus intraradices', 'Rhizophagus irregularis', '🕸️', 'The workhorse mycorrhiza sold to farmers worldwide.'],
  ['mycorrhizal-rhizophagus', 'Rhizophagus clarus', 'Rhizophagus clarus', '🕸️', 'A root fungus that helps soybeans drink phosphorus.'],
  ['mycorrhizal-rhizophagus', 'Gigaspora margarita', 'Gigaspora margarita', '🕸️', 'A giant-spored mycorrhiza that partners with tropical trees.'],
  ['endogone', 'Endogone pisiformis', 'Endogone pisiformis', '🕸️', 'A truffle-like root fungus that feeds on soil sugars.'],
  ['endogone', 'Endogone lactiflua', 'Endogone lactiflua', '🕸️', 'A pale underground fungus of pine forests.'],
  ['microsporidian', 'Nosema apis', 'Nosema apis', '🐝', 'The microsporidian parasite that sickens honey bee colonies.'],
  ['microsporidian', 'Encephalitozoon cuniculi', 'Encephalitozoon cuniculi', '🐇', 'A tiny spore parasite of rabbits with a harpoon-like infection tube.'],
  ['lichen-crust', 'Map lichen', 'Rhizocarpon geographicum', '🗺️', 'The lichen that paints rocks like yellow maps — and dates glaciers.'],
  ['lichen-crust', 'Common orange lichen', 'Xanthoria parietina', '🟠', 'The bright orange crust of rooftops and sea cliffs.'],
  ['lichen-orange', 'Sunburst lichen', 'Xanthoria elegans', '🟠', 'The lichen that survived 18 months in open space.'],
  ['lichen-orange', 'Maritime sunburst', 'Xanthoria calcicola', '🟠', 'An orange shield lichen of sunny limestone.'],
  ['lichen-map', 'Yellow map lichen', 'Rhizocarpon lecanorinum', '🗺️', 'A slow-growing crust that can be thousands of years old.'],
  ['lichen-map', 'Green map lichen', 'Rhizocarpon viridiatrum', '🗺️', 'A chartreuse crust lichen of mountain rock.'],
  ['lichen-leafy', 'Dog lichen', 'Peltigera canina', '🍃', 'A leafy lichen once used as a rabies cure.'],
  ['lichen-leafy', 'Lungwort lichen', 'Lobaria pulmonaria', '🍃', 'The lung-shaped lichen that signals ancient forests.'],
  ['lichen-bushy', 'Reindeer lichen', 'Cladonia rangiferina', '🦌', 'The fluffy lichen that feeds caribou through Arctic winters.'],
  ['lichen-bushy', 'British soldiers', 'Cladonia cristatella', '🔴', 'The lichen whose red caps look like tiny redcoats.'],
  ['lichen-powder', 'Fairy cups', 'Cladonia fimbriata', '🧚', 'A pixie-cup lichen of bare soil and stumps.'],
  ['lichen-powder', 'Pixie cup lichen', 'Cladonia pyxidata', '🧚', 'A goblet-shaped lichen with cups for raindrops.'],
]
