// GrinKingdom seed rows — plants.

export const PLANT_ROWS = [
  ['tree', 'London plane', 'Platanus × acerifolia', '🌳', 'The patchwork-bark street tree of city squares.'],
  ['tree', 'Sweet chestnut', 'Castanea sativa', '🌰', 'The tree that fed European villages for centuries.'],
  ['tree-betula', 'Silver birch', 'Betula pendula', '🌳', 'The paper-white pioneer of northern woods.'],
  ['tree-betula', 'Paper birch', 'Betula papyrifera', '🌳', 'The canoe-bark birch of North America.'],
  ['tree-rosaceae', 'Wild cherry', 'Prunus avium', '🍒', 'The spring-blossom tree of woodlands and orchards.'],
  ['tree-rosaceae', 'Rowan', 'Sorbus aucuparia', '🌳', 'The mountain ash whose red berries feed winter birds.'],
  ['tree-ulmaceae', 'English elm', 'Ulmus procera', '🌳', 'The cathedral-arch tree nearly wiped out by Dutch elm disease.'],
  ['tree-ulmaceae', 'Hackberry', 'Celtis occidentalis', '🌳', 'The tough city tree with warty bark.'],
  ['tree-moraceae', 'Common fig', 'Ficus carica', '🍈', 'The tree whose "fruit" is secretly a flower turned inside out.'],
  ['tree-moraceae', 'Banyan', 'Ficus benghalensis', '🌳', 'The walking tree that drops roots from its branches.'],
  ['tree-salicaceae', 'Weeping willow', 'Salix babylonica', '🌳', 'The riverbank tree that seems to cry into the water.'],
  ['tree-salicaceae', 'Quaking aspen', 'Populus tremuloides', '🌳', 'The shimmering clone-forest — one root system, thousands of trunks.'],
  ['tree-sapindaceae', 'Sugar maple', 'Acer saccharum', '🍁', 'The tree that sweetens pancakes and paints autumns red.'],
  ['tree-sapindaceae', 'Horse chestnut', 'Aesculus hippocastanum', '🌰', 'The conker tree with candle flowers and spiky fruit.'],
  ['tree-anacardiaceae', 'Mango', 'Mangifera indica', '🥭', 'The most-eaten fruit tree in the world.'],
  ['tree-anacardiaceae', 'Cashew', 'Anacardium occidentale', '🥜', 'The tree whose nut wears a toxic glove.'],
  ['tree-meliaceae', 'Mahogany', 'Swietenia macrophylla', '🪵', 'The reddish hardwood that built fine furniture.'],
  ['tree-meliaceae', 'Neem', 'Azadirachta indica', '🌿', 'The "village pharmacy" tree of India.'],
  ['tree-rutaceae', 'Orange tree', 'Citrus × sinensis', '🍊', 'A hybrid fruit tree that conquered breakfast.'],
  ['tree-rutaceae', 'Lemon tree', 'Citrus limon', '🍋', 'The sour-sunshine tree of Mediterranean groves.'],
  ['tree-malvaceae', 'Kapok', 'Ceiba pentandra', '🌳', 'The jungle giant whose fluff once stuffed life jackets.'],
  ['tree-malvaceae', 'Cacao tree', 'Theobroma cacao', '🍫', 'The "food of the gods" tree behind every chocolate bar.'],
  ['tree-dipterocarpaceae', 'Meranti', 'Shorea robusta', '🌳', 'The towering timber tree of Southeast Asian rainforests.'],
  ['tree-dipterocarpaceae', 'Kapur', 'Dryobalanops aromatica', '🌳', 'The camphor-scented giant of Borneo.'],
  ['tree-myrtaceae', 'Eucalyptus', 'Eucalyptus globulus', '🌿', 'The blue gum that perfumes Australia and feeds koalas.'],
  ['tree-myrtaceae', 'Clove tree', 'Syzygium aromaticum', '🌿', 'The spice tree whose dried buds flavored empires.'],
  ['tree-fabaceae', 'Flamboyant', 'Delonix regia', '🔥', 'The flame tree that sets tropical streets ablaze.'],
  ['tree-fabaceae', 'Black locust', 'Robinia pseudoacacia', '🌳', 'The tough nitrogen-fixing tree with fragrant flowers.'],
  ['tree-magnoliaceae', 'Tulip tree', 'Liriodendron tulipifera', '🌷', 'The tree with tulip flowers and square-cut leaves.'],
  ['tree-magnoliaceae', 'Star magnolia', 'Magnolia stellata', '🌸', 'The early-spring star-bloom of gardens.'],
  ['tree-lauraceae', 'Avocado', 'Persea americana', '🥑', 'The alligator pear that conquered brunch.'],
  ['tree-lauraceae', 'Bay laurel', 'Laurus nobilis', '🌿', 'The wreath-crown tree of ancient champions.'],
  ['tree-ebenaceae', 'Ebony', 'Diospyros ebenum', '🪵', 'The near-black hardwood of piano keys.'],
  ['tree-ebenaceae', 'Persimmon', 'Diospyros kaki', '🍊', 'The autumn orange fruit that ripens after frost.'],
  ['tree-theaceae', 'Tea plant', 'Camellia sinensis', '🍵', 'One bush, six cups: green, black, oolong, white, yellow and pu-erh.'],
  ['tree-theaceae', 'Camellia', 'Camellia japonica', '🌸', 'The winter rose of East Asian gardens.'],
  ['tree-oleaceae', 'Olive tree', 'Olea europaea', '🫒', 'The gnarled tree that can live for two thousand years.'],
  ['tree-oleaceae', 'European ash', 'Fraxinus excelsior', '🌳', 'The hurley-stick tree of Celtic legend.'],
  ['tree-bignoniaceae', 'Jacaranda', 'Jacaranda mimosifolia', '💜', 'The purple-rain tree of November avenues.'],
  ['tree-bignoniaceae', 'Trumpet vine', 'Campsis radicans', '🎺', 'The climbing trumpet-flower of fence lines.'],
  ['tree-euphorb', 'Rubber tree', 'Hevea brasiliensis', '🌳', 'The Amazon tree that made the world bounce.'],
  ['tree-euphorb', 'Candlenut', 'Aleurites moluccanus', '🌳', 'The Polynesian tree whose nuts once burned as candles.'],
  ['mangrove', 'Red mangrove', 'Rhizophora mangle', '🌊', 'The stilt-rooted tree that walks into the sea.'],
  ['mangrove', 'Black mangrove', 'Avicennia germinans', '🌊', 'The mangrove with breathing snorkel roots.'],
  ['mangrove', 'White mangrove', 'Laguncularia racemosa', '🌊', 'The lagoon mangrove that filters salt with special glands.'],
  ['palm', 'Coconut palm', 'Cocos nucifera', '🥥', 'The tree of a thousand uses, drifting between islands.'],
  ['palm', 'Date palm', 'Phoenix dactylifera', '🌴', 'The desert palm that has fed oases for 6,000 years.'],
  ['palm', 'Oil palm', 'Elaeis guineensis', '🌴', 'The most productive oil crop on Earth — for better and worse.'],
  ['pine', 'Scots pine', 'Pinus sylvestris', '🌲', 'The rugged red-barked pine of northern forests.'],
  ['pine', 'Sugar pine', 'Pinus lambertiana', '🌲', 'The king of pines, with cones half a metre long.'],
  ['pine', 'Bristlecone pine', 'Pinus longaeva', '🌲', 'The gnarled survivor that can outlive civilizations.'],
  ['cypress', 'Bald cypress', 'Taxodium distichum', '🌲', 'The swamp conifer with woody "knees" poking from the water.'],
  ['cypress', 'Italian cypress', 'Cupressus sempervirens', '🌲', 'The pencil-thin sentinel of Tuscan hills.'],
  ['cypress', 'Coast redwood', 'Sequoia sempervirens', '🌲', 'The tallest tree on Earth — up to 115 metres of patience.'],
  ['yew', 'European yew', 'Taxus baccata', '🌲', 'The churchyard evergreen that can live for millennia.'],
  ['yew', 'Pacific yew', 'Taxus brevifolia', '🌲', 'The tree whose bark gave us a cancer-fighting drug.'],
  ['araucaria', 'Monkey puzzle', 'Araucaria araucana', '🐒', 'The spiky dinosaur-age tree that puzzled even monkeys.'],
  ['araucaria', 'Norfolk Island pine', 'Araucaria heterophylla', '🌲', 'The symmetrical living Christmas tree of living rooms.'],
  ['ginkgo', 'Ginkgo', 'Ginkgo biloba', '🍂', 'The living fossil whose fan leaves turn pure gold in autumn.'],
  ['ginkgo', 'Maidenhair tree', 'Ginkgo biloba f. epiphylla', '🍂', 'A ginkgo oddity that sprouts leaves from its leaves.'],
  ['tree-fern', 'Tree fern', 'Dicksonia antarctica', '🌿', 'The fern that grows a trunk and shades whole gullies.'],
  ['tree-fern', 'Silver fern', 'Cyathea dealbata', '🌿', 'New Zealand\'s emblem — its fronds flash silver in moonlight.'],
  ['flower-asteraceae', 'Daisy', 'Bellis perennis', '🌼', 'The lawn star whose name means "day\'s eye".'],
  ['flower-asteraceae', 'Cornflower', 'Centaurea cyanus', '💙', 'The field-blue bloom that followed farmers for centuries.'],
  ['flower-campanulaceae', 'Harebell', 'Campanula rotundifolia', '🔔', 'The bluebell of windy grasslands.'],
  ['flower-campanulaceae', 'Canterbury bells', 'Campanula medium', '🔔', 'The cottage-garden bellflower of midsummer.'],
  ['flower-rosaceae', 'Wild rose', 'Rosa canina', '🌹', 'The hedgerow rose whose hips brew a wartime syrup.'],
  ['flower-rosaceae', 'Meadowsweet', 'Filipendula ulmaria', '🌼', 'The almond-scented meadow herb behind aspirin\'s name.'],
  ['flower-fabaceae', 'Sweet pea', 'Lathyrus odoratus', '🌺', 'The climbing fragrance bomb of cottage gardens.'],
  ['flower-fabaceae', 'Lupin', 'Lupinus polyphyllus', '🌺', 'The spired nitrogen-fixer that colonized road verges.'],
  ['flower-lamiaceae', 'Lavender', 'Lavandula angustifolia', '💜', 'The purple field that perfumes Provence.'],
  ['flower-lamiaceae', 'Peppermint', 'Mentha × piperita', '🌿', 'The hybrid mint that cools your breath and your tea.'],
  ['flower-plantaginaceae', 'Foxglove', 'Digitalis purpurea', '💜', 'The purple spire that both heals and poisons hearts.'],
  ['flower-plantaginaceae', 'Snapdragon', 'Antirrhinum majus', '🐉', 'The flower that snaps like a dragon\'s jaw.'],
  ['flower-solanaceae', 'Potato', 'Solanum tuberosum', '🥔', 'The Andean tuber that fed the Industrial Revolution.'],
  ['flower-solanaceae', 'Tomato', 'Solanum lycopersicum', '🍅', 'The "wolf peach" that conquered world cuisine.'],
  ['flower-convolvulaceae', 'Morning glory', 'Ipomoea purpurea', '🌅', 'The dawn-flowering vine that dies by noon.'],
  ['flower-convolvulaceae', 'Sweet potato', 'Ipomoea batatas', '🍠', 'The sweet tuber vine that fed Pacific voyages.'],
  ['flower-apiaceae', 'Carrot', 'Daucus carota', '🥕', 'The wild Queen Anne\'s lace turned orange by gardeners.'],
  ['flower-apiaceae', 'Fennel', 'Foeniculum vulgare', '🌿', 'The licorice-flavored herb of seashores and kitchens.'],
  ['flower-ranunculaceae', 'Buttercup', 'Ranunculus acris', '🟡', 'The glossy meadow flower that "tells" if you like butter.'],
  ['flower-ranunculaceae', 'Marsh marigold', 'Caltha palustris', '🟡', 'The golden splash of spring wetlands.'],
  ['flower-papaveraceae', 'Poppy', 'Papaver rhoeas', '🌹', 'The cornfield poppy that became remembrance itself.'],
  ['flower-papaveraceae', 'Opium poppy', 'Papaver somniferum', '🌹', 'The poppy that gives painkillers, seeds and seedier things.'],
  ['flower-liliaceae', 'Snake\'s head fritillary', 'Fritillaria meleagris', '🏵️', 'The checkered chessboard flower of damp meadows.'],
  ['flower-liliaceae', 'Turk\'s cap lily', 'Lilium martagon', '🏵️', 'The turban lily of high mountain meadows.'],
  ['flower-amaryllidaceae', 'Daffodil', 'Narcissus pseudonarcissus', '🌼', 'The golden trumpet that declares spring has won.'],
  ['flower-amaryllidaceae', 'Snowdrop', 'Galanthus nivalis', '🤍', 'The first brave bloom through winter snow.'],
  ['flower-orchidaceae', 'Bee orchid', 'Ophrys apifera', '🐝', 'The orchid that dresses up as a bee to fool real bees.'],
  ['flower-orchidaceae', 'Lady\'s slipper', 'Cypripedium calceolus', '👠', 'The yellow slipper orchid of ancient woodlands.'],
  ['flower-iridaceae', 'Bearded iris', 'Iris germanica', '🌈', 'The rainbow flower of old garden walls.'],
  ['flower-iridaceae', 'Saffron crocus', 'Crocus sativus', '🧡', 'The autumn crocus whose stigmas are worth more than gold.'],
  ['flower-asphodelaceae', 'Daylily', 'Hemerocallis fulva', '🟠', 'The one-day flower that keeps coming back.'],
  ['flower-asphodelaceae', 'Red hot poker', 'Kniphofia uvaria', '🔥', 'The torch-lily that glows like embers.'],
  ['flower-bromeliaceae', 'Pineapple', 'Ananas comosus', '🍍', 'The berry that wears a crown and takes two years to grow.'],
  ['flower-bromeliaceae', 'Spanish moss', 'Tillandsia usneoides', '🌫️', 'The air plant that drapes southern oaks in grey.'],
  ['flower-zingiberaceae', 'Ginger', 'Zingiber officinale', '🫚', 'The spicy rhizome that has spiced Asia for 5,000 years.'],
  ['flower-zingiberaceae', 'Turmeric', 'Curcuma longa', '🟡', 'The golden root that dyes curry and lab coats alike.'],
  ['flower-musaceae', 'Banana', 'Musa acuminata', '🍌', 'The giant herb that is actually the world\'s favorite fruit.'],
  ['flower-musaceae', 'Plantain', 'Musa × paradisiaca', '🍌', 'The starchy cooking banana of tropical kitchens.'],
  ['flower-nymphaeaceae', 'White water lily', 'Nymphaea alba', '🤍', 'The floating star of still ponds.'],
  ['flower-nymphaeaceae', 'Blue lotus', 'Nymphaea caerulea', '💙', 'The sacred Nile flower of ancient Egypt.'],
  ['flower-nelumbonaceae', 'Sacred lotus', 'Nelumbo nucifera', '🪷', 'The self-cleaning flower that rises unstained from mud.'],
  ['flower-nelumbonaceae', 'American lotus', 'Nelumbo lutea', '🪷', 'The pale yellow lotus of North American bays.'],
  ['flower-geraniaceae', 'Wild geranium', 'Geranium maculatum', '💜', 'The woodland cranesbill of spring forests.'],
  ['flower-geraniaceae', 'Zonal geranium', 'Pelargonium × hortorum', '❤️', 'The balcony-box bloom of summer windows.'],
  ['flower-violaceae', 'Sweet violet', 'Viola odorata', '💜', 'The perfumed woodland violet of spring.'],
  ['flower-violaceae', 'Pansy', 'Viola × wittrockiana', '😊', 'The cheerful face-flower of window boxes.'],
  ['flower-malvaceae', 'Hibiscus', 'Hibiscus rosa-sinensis', '🌺', 'The tropical trumpet that blooms for just one day.'],
  ['flower-malvaceae', 'Hollyhock', 'Alcea rosea', '🌺', 'The cottage-garden skyscraper of spires.'],
  ['flower-cucurbitaceae', 'Cucumber', 'Cucumis sativus', '🥒', 'The cool vine fruit that is 96% water.'],
  ['flower-cucurbitaceae', 'Pumpkin', 'Cucurbita pepo', '🎃', 'The autumn giant that can weigh as much as a car.'],
  ['flower-begoniaceae', 'Begonia', 'Begonia semperflorens', '🌸', 'The wax-leaf bedding plant of city parks.'],
  ['flower-begoniaceae', 'Angel wing begonia', 'Begonia coccinea', '🌸', 'The spotted-wing houseplant with hanging blooms.'],
  ['flower-primulaceae', 'Primrose', 'Primula vulgaris', '🌼', 'The "first rose" that opens spring in the hedgerows.'],
  ['flower-primulaceae', 'Cowslip', 'Primula veris', '🌼', 'The nodding golden bells of old meadows.'],
  ['flower-ericaceae', 'Heather', 'Calluna vulgaris', '💜', 'The purple carpet of moors and mountains.'],
  ['flower-ericaceae', 'Blueberry', 'Vaccinium corymbosum', '🫐', 'The bog bush whose berries paint tongues blue.'],
  ['flower-cornaceae', 'Dogwood', 'Cornus florida', '🌸', 'The spring tree with flower-like white bracts.'],
  ['flower-cornaceae', 'Cornelian cherry', 'Cornus mas', '🌸', 'The early-yellow dogwood of old gardens.'],
  ['flower-gentianaceae', 'Spring gentian', 'Gentiana verna', '💙', 'The startling alpine blue of limestone turf.'],
  ['flower-gentianaceae', 'Fringed gentian', 'Gentianopsis crinita', '💙', 'The fringed blue jewel of autumn meadows.'],
  ['flower-rubiaceae', 'Coffee plant', 'Coffea arabica', '☕', 'The highland shrub behind 60% of the world\'s coffee.'],
  ['flower-rubiaceae', 'Gardenia', 'Gardenia jasminoides', '🤍', 'The creamy flower whose scent fills summer nights.'],
  ['flower-apocynaceae', 'Frangipani', 'Plumeria rubra', '🌸', 'The lei flower of tropical islands.'],
  ['flower-apocynaceae', 'Periwinkle', 'Catharanthus roseus', '🌸', 'The humble flower that gave us leukemia drugs.'],
  ['flower-crassulaceae', 'Jade plant', 'Crassula ovata', '🪴', 'The lucky money-plant of windowsills.'],
  ['flower-crassulaceae', 'Houseleek', 'Sempervivum tectorum', '🪴', 'The "live-forever" rosette that once guarded roofs from lightning.'],
  ['flower-cactaceae', 'Prickly pear', 'Opuntia ficus-indica', '🌵', 'The pad cactus whose fruit feeds deserts and margaritas.'],
  ['flower-cactaceae', 'Christmas cactus', 'Schlumbergera truncata', '🎄', 'The forest cactus that blooms for the holidays.'],
  ['flower-amaranthaceae', 'Beetroot', 'Beta vulgaris', '🟣', 'The root that stains everything ruby — sugar beets too.'],
  ['flower-amaranthaceae', 'Quinoa', 'Chenopodium quinoa', '🌾', 'The Andean "mother grain" that feeds astronauts.'],
  ['flower-aizoaceae', 'Living stones', 'Lithops lesliei', '🪨', 'The pebble plant that hides in plain sight.'],
  ['flower-aizoaceae', 'Ice plant', 'Mesembryanthemum crystallinum', '❄️', 'The glittering succulent that looks dusted with frost.'],
  ['flower-polygonaceae', 'Rhubarb', 'Rheum rhabarbarum', '🌿', 'The pie plant whose leaves are poisonous, stalks delicious.'],
  ['flower-polygonaceae', 'Japanese knotweed', 'Fallopia japonica', '🌿', 'The concrete-cracking invader that grows through walls.'],
  ['flower-caryophyllaceae', 'Carnation', 'Dianthus caryophyllus', '💐', 'The ruffled flower of boutonnieres and May Day.'],
  ['flower-caryophyllaceae', 'Red campion', 'Silene dioica', '🌸', 'The pink woodland flower that glows at dusk.'],
  ['flower-linaceae', 'Flax', 'Linum usitatissimum', '💙', 'The sky-blue flower that clothes us as linen.'],
  ['flower-linaceae', 'Scarlet flax', 'Linum grandiflorum', '❤️', 'The annual red flax of sunny borders.'],
  ['flower-vitaceae', 'Grapevine', 'Vitis vinifera', '🍇', 'The ancient vine behind every wine ever poured.'],
  ['flower-vitaceae', 'Virginia creeper', 'Parthenocissus quinquefolia', '🍁', 'The climber that turns walls crimson each fall.'],
  ['succulent-euphorbia', 'Candelabra spurge', 'Euphorbia ingens', '🕯️', 'The tree-like spurge that looks like a cactus but is not.'],
  ['succulent-euphorbia', 'Baseball plant', 'Euphorbia obesa', '⚾', 'The round spurge that looks exactly like a baseball.'],
  ['grass', 'Wheat', 'Triticum aestivum', '🌾', 'The grass that built civilization, one loaf at a time.'],
  ['grass', 'Rice', 'Oryza sativa', '🍚', 'The paddy grass that feeds half of humanity.'],
  ['grass', 'Maize', 'Zea mays', '🌽', 'The engineered-by-people grass of the Americas.'],
  ['grass', 'Meadow fescue', 'Festuca pratensis', '🌾', 'The pasture grass of cows and haylofts.'],
  ['grass', 'Miscanthus', 'Miscanthus × giganteus', '🌾', 'The elephant grass grown for green energy.'],
  ['bamboo', 'Moso bamboo', 'Phyllostachys edulis', '🎋', 'The timber bamboo that can grow a metre a day.'],
  ['bamboo', 'Lucky bamboo', 'Dracaena sanderiana', '🎋', 'The spiral-stemmed houseplant that is not bamboo at all.'],
  ['grass-cyperaceae', 'Papyrus', 'Cyperus papyrus', '📜', 'The Nile sedge that became the first paper.'],
  ['grass-cyperaceae', 'Water chestnut sedge', 'Eleocharis dulcis', '🌰', 'The crunchy corm of Chinese stir-fries.'],
  ['grass-typhaceae', 'Bulrush', 'Typha latifolia', '🌾', 'The hot-dog cattail of ponds and marshes.'],
  ['grass-typhaceae', 'Dwarf bulrush', 'Typha minima', '🌾', 'The miniature cattail of pond edges.'],
  ['fern', 'Hart\'s tongue fern', 'Asplenium scolopendrium', '🌿', 'The strap-leaved fern of shaded banks.'],
  ['fern', 'Maidenhair fern', 'Adiantum capillus-veneris', '🌿', 'The delicate fern that repels water with black-stemmed fronds.'],
  ['fern', 'Royal fern', 'Osmunda regalis', '🌿', 'The regal fern of stream banks and bogs.'],
  ['fern-bracken', 'Bracken', 'Pteridium aquilinum', '🌿', 'The most widespread fern on Earth — and the most stubborn.'],
  ['fern-bracken', 'Ostrich fern', 'Matteuccia struthiopteris', '🌿', 'The fern whose fiddleheads are a spring delicacy.'],
  ['horsetail', 'Field horsetail', 'Equisetum arvense', '🌿', 'The living fossil that scours pans with silica.'],
  ['horsetail', 'Great horsetail', 'Equisetum telmateia', '🌿', 'The giant reed of ditches, older than dinosaurs.'],
  ['clubmoss', 'Stag\'s horn clubmoss', 'Lycopodium clavatum', '🌿', 'The trailing spore-plant that once lit theater flashes.'],
  ['clubmoss', 'Fir clubmoss', 'Huperzia selago', '🌿', 'The ancient spore plant of mountain crags.'],
  ['moss', 'Feather moss', 'Pleurozium schreberi', '🌱', 'The soft green carpet of boreal forests.'],
  ['moss', 'Cushion moss', 'Leucobryum glaucum', '🌱', 'The silvery pincushion of dry woodlands.'],
  ['sphagnum', 'Sphagnum moss', 'Sphagnum palustre', '🌱', 'The bog moss that holds 20 times its weight in water.'],
  ['sphagnum', 'Red bog moss', 'Sphagnum capillifolium', '🌱', 'The crimson moss that slowly builds peatlands.'],
  ['liverwort', 'Common liverwort', 'Marchantia polymorpha', '🌱', 'The umbrella-plant that thrives between paving stones.'],
  ['liverwort', 'Snakewort', 'Conocephalum conicum', '🌱', 'The snakeskin liverwort of wet rocks.'],
  ['hornwort', 'Field hornwort', 'Anthoceros agrestis', '🌱', 'The tiny plant that hosts nitrogen-fixing cyanobacteria.'],
  ['hornwort', 'Phaeoceros', 'Phaeoceros laevis', '🌱', 'A horned plant of damp soil, older than flowers.'],
  ['carnivorous-sundew', 'Round-leaved sundew', 'Drosera rotundifolia', '🪰', 'The sparkling bog trap that glues insects with jeweled drops.'],
  ['carnivorous-sundew', 'Cape sundew', 'Drosera capensis', '🪰', 'The windowsill sundew that curls around its prey.'],
  ['carnivorous-pitcher', 'Purple pitcher plant', 'Sarracenia purpurea', '🏺', 'The North American bog pitcher that drowns its dinners.'],
  ['carnivorous-pitcher', 'Cobra lily', 'Darlingtonia californica', '🐍', 'The pitcher plant with fangs and false windows.'],
  ['carnivorous-tropical-pitcher', 'Monkey cup', 'Nepenthes rajah', '🏺', 'The giant pitcher that can hold two litres of digestive soup.'],
  ['carnivorous-tropical-pitcher', 'Albomarginata pitcher', 'Nepenthes albomarginata', '🏺', 'The pitcher that baits termites with a fuzzy white collar.'],
  ['carnivorous-bladderwort', 'Common bladderwort', 'Utricularia vulgaris', '🎈', 'The fastest trap in the plant world — it sucks prey in a millisecond.'],
  ['carnivorous-bladderwort', 'Humped bladderwort', 'Utricularia gibba', '🎈', 'The tiny plant with a near-minimal genome and lightning traps.'],
  ['aquatic-duckweed', 'Common duckweed', 'Lemna minor', '🟢', 'The world\'s smallest flowering plant, doubling in days.'],
  ['aquatic-duckweed', 'Giant duckweed', 'Spirodela polyrhiza', '🟢', 'The multi-rooted duckweed of still ponds.'],
  ['aquatic-seagrass', 'Eelgrass', 'Zostera marina', '🌊', 'The underwater meadow that shelters seahorses.'],
  ['aquatic-seagrass', 'Neptune grass', 'Posidonia oceanica', '🌊', 'The Mediterranean seagrass that can live 100,000 years.'],
]
