// GrinKingdom seed rows — viruses.
// Row format: [groupKey, name, sci, emoji, tagline, status?, size?, lifespan?]

export const VIRUS_ROWS = [
  ['coronavirus', 'MERS-CoV', 'Middle East respiratory syndrome coronavirus', '🐪', 'The desert cousin of SARS-CoV-2, first found in camels.'],
  ['coronavirus', 'Human coronavirus 229E', 'Human coronavirus 229E', '🤧', 'One of the four coronaviruses behind the common cold.'],
  ['coronavirus', 'Human coronavirus NL63', 'Human coronavirus NL63', '🤧', 'A common-cold coronavirus that uses the same door as SARS-CoV-2.'],
  ['coronavirus', 'Human coronavirus HKU1', 'Human coronavirus HKU1', '🤧', 'A cold virus named after Hong Kong University, discovered in 2005.'],
  ['coronavirus', 'Mouse hepatitis virus', 'Murine coronavirus', '🐭', 'The lab-mouse coronavirus scientists study to understand SARS.'],
  ['influenzavirus', 'Influenza B', 'Betainfluenzavirus influenzae', '🤒', 'The flu type that mostly circulates only in humans.'],
  ['influenzavirus', 'Influenza C', 'Gammainfluenzavirus influenzae', '🤒', 'A mild, sniffly flu that almost never causes big outbreaks.'],
  ['influenzavirus', 'Influenza D', 'Deltainfluenzavirus influenzae', '🐄', 'A flu virus found mainly in cattle, pigs and sheep.'],
  ['paramyxovirus', 'Measles virus', 'Morbillivirus hominis', '🔴', 'One of the most contagious viruses known — 9 out of 10 exposed people catch it.'],
  ['paramyxovirus', 'Mumps virus', 'Mumps orthorubulavirus', '🎈', 'The virus behind puffy chipmunk cheeks.'],
  ['paramyxovirus', 'RSV', 'Human orthopneumovirus', '👶', 'The winter virus that keeps pediatric wards busy.'],
  ['paramyxovirus', 'Nipah virus', 'Nipah henipavirus', '🦇', 'A brain-infecting virus that spills over from fruit bats.'],
  ['filovirus', 'Ebola virus', 'Orthoebolavirus zairense', '🩸', 'A filament virus with a fearsome reputation, named after a river.'],
  ['filovirus', 'Marburg virus', 'Orthomarburgvirus marburgense', '🩸', 'Ebola\'s cousin, traced to green monkeys in 1967.'],
  ['filovirus', 'Reston virus', 'Orthoebolavirus restonense', '🐒', 'The Ebola cousin that infects monkeys but, luckily, not people.'],
  ['rhabdovirus', 'Rabies virus', 'Lyssavirus rabies', '🐕', 'A bullet-shaped virus that rewires the brain to crave biting.'],
  ['rhabdovirus', 'Vesicular stomatitis virus', 'Vesiculovirus indiana', '🐄', 'A cattle virus whose bullet shape made it an electron-microscope pin-up.'],
  ['flavivirus', 'Dengue virus', 'Dengue virus', '🦟', 'The "breakbone fever" virus delivered by tiger mosquitoes.'],
  ['flavivirus', 'Zika virus', 'Zika virus', '🦟', 'A mosquito virus that crossed oceans to shake the 2016 Olympics.'],
  ['flavivirus', 'Yellow fever virus', 'Yellow fever virus', '🟡', 'The virus that turned whole cities yellow — and helped finish the Panama Canal.'],
  ['flavivirus', 'West Nile virus', 'West Nile virus', '🐦', 'A bird virus that mosquitoes pass along to people.'],
  ['flavivirus', 'Hepatitis C virus', 'Hepacivirus hominis', '🧪', 'A liver virus that hid for decades before being named in 1989.'],
  ['picornavirus', 'Poliovirus', 'Enterovirus C', '🦵', 'The virus that put swimming pools off-limits every summer — before vaccines tamed it.'],
  ['picornavirus', 'Rhinovirus', 'Rhinovirus A', '🤧', 'The undisputed champion cause of the common cold.'],
  ['picornavirus', 'Hepatitis A virus', 'Hepatovirus ahepa', '🍽️', 'A picnic-ruining virus spread by contaminated food and water.'],
  ['picornavirus', 'Foot-and-mouth disease virus', 'Foot-and-mouth disease virus', '🐄', 'So contagious it can shut down a whole country\'s livestock trade.'],
  ['calicivirus', 'Norovirus', 'Norwalk virus', '🚢', 'The infamous "cruise-ship virus" that turns vacations into quarantines.'],
  ['calicivirus', 'Sapovirus', 'Sapporo virus', '🍜', 'Norovirus\'s quieter cousin, named after Sapporo, Japan.'],
  ['reovirus', 'Rotavirus', 'Rotavirus A', '🍼', 'A wheel-shaped virus that once made every baby\'s first years miserable.'],
  ['reovirus', 'Bluetongue virus', 'Bluetongue virus', '🐑', 'A midge-borne virus that turns sheep tongues blue.'],
  ['herpesvirus', 'HSV-1', 'Human alphaherpesvirus 1', '💋', 'The virus behind cold sores — a lifelong resident of your nerve cells.'],
  ['herpesvirus', 'HSV-2', 'Human alphaherpesvirus 2', '💋', 'The other herpes simplex — it hides in nerves and waits.'],
  ['herpesvirus', 'Varicella zoster virus', 'Human alphaherpesvirus 3', '🐔', 'One virus, two acts: chickenpox in kids, shingles in adults.'],
  ['herpesvirus', 'Epstein–Barr virus', 'Human gammaherpesvirus 4', '😴', 'The "kissing disease" virus that nearly everyone carries by age 40.'],
  ['herpesvirus', 'Cytomegalovirus', 'Human betaherpesvirus 5', '👁️', 'A stealthy herpesvirus most people never notice they have.'],
  ['poxvirus', 'Variola virus', 'Variola virus', '🏺', 'The brick-shaped virus that humanity officially erased in 1980.'],
  ['poxvirus', 'Vaccinia virus', 'Vaccinia virus', '🐄', 'The cowpox relative that became the world\'s first vaccine.'],
  ['poxvirus', 'Cowpox virus', 'Cowpox virus', '🐄', 'The mild pox milkmaids caught — and it saved humanity from smallpox.'],
  ['poxvirus', 'Mpox virus', 'Monkeypox virus', '🐒', 'A smallpox relative that stepped out of the rainforest in 2022.'],
  ['adenovirus', 'Human adenovirus C', 'Human adenovirus C', '👁️', 'A spiky 20-sided virus behind colds, pinkeye and tummy bugs.'],
  ['papillomavirus', 'HPV 16', 'Human papillomavirus 16', '🎗️', 'The wart virus that taught us vaccines can prevent cancer.'],
  ['parvovirus', 'Parvovirus B19', 'Primate erythroparvovirus 1', '🩸', 'The tiniest DNA virus, famous for "slapped cheek" disease.'],
  ['parvovirus', 'Canine parvovirus', 'Carnivore protoparvovirus 1', '🐶', 'A puppy plague that appeared out of nowhere in the 1970s.'],
  ['hepadnavirus', 'Hepatitis B virus', 'Hepatitis B virus', '🧬', 'A DNA virus that slips into liver cells and refuses to leave.'],
  ['retrovirus', 'HIV-2', 'Human immunodeficiency virus 2', '🐒', 'The West African cousin of HIV-1, descended from mangabey monkeys.'],
  ['retrovirus', 'SIV', 'Simian immunodeficiency virus', '🐒', 'The ape virus that jumped into humans and became HIV.'],
  ['retrovirus', 'HTLV-1', 'Primate T-lymphotropic virus 1', '🧬', 'The first human retrovirus ever discovered, found in 1980.'],
  ['bunyavirus', 'Hantavirus', 'Hantaan orthohantavirus', '🐁', 'A mouse-borne virus that can turn a dusty barn into a danger zone.'],
  ['bunyavirus', 'Crimean-Congo hemorrhagic fever virus', 'Crimean-Congo hemorrhagic fever virus', '🐐', 'A tick-borne fever virus with a kill-rate that worries hospitals.'],
  ['bunyavirus', 'Rift Valley fever virus', 'Rift Valley fever phlebovirus', '🐏', 'A mosquito-borne virus that hits sheep and shepherds across Africa.'],
  ['arenavirus', 'Lassa virus', 'Lassa mammarenavirus', '🐀', 'A rat-borne virus named after a Nigerian town.'],
  ['arenavirus', 'Lymphocytic choriomeningitis virus', 'Lymphocytic choriomeningitis virus', '🐹', 'The pet-hamster virus that gave immunology its first good model.'],
  ['phage-myo', 'Phage T2', 'Escherichia virus T2', '🧪', 'The phage from the 1952 blender experiment that proved DNA is the genetic material.'],
  ['phage-myo', 'Phage P1', 'Escherichia virus P1', '🚕', 'A phage that shuttles genes between bacteria like a molecular taxi.'],
  ['phage-sipho', 'Phage lambda', 'Escherichia virus Lambda', '🧪', 'The phage that taught us how genes switch on and off.'],
  ['phage-podo', 'Phage T7', 'Escherichia virus T7', '⚡', 'A workhorse phage that can copy itself in 15 minutes flat.'],
  ['phage-filamentous', 'Phage M13', 'Escherichia virus M13', '🧵', 'A spaghetti-shaped phage that labs use to display proteins like flags.'],
  ['phage-micro', 'Phage ΦX174', 'Escherichia virus phiX174', '🔬', 'The first genome ever fully sequenced — a tiny circle of 5,386 letters.'],
  ['phage-rna', 'Phage MS2', 'Escherichia virus MS2', '🔬', 'An RNA phage so simple it helped crack the genetic code.'],
  ['giant-virus', 'Mimivirus', 'Mimivirus bradfordmassiliense', '🦕', 'The first "giant virus" — so big scientists mistook it for a bacterium.'],
  ['giant-virus', 'Pandoravirus', 'Pandoravirus dulcis', '🏺', 'A giant virus with a genome bigger than some bacteria — mostly mystery genes.'],
  ['giant-virus', 'Pithovirus', 'Pithovirus sibericum', '🧊', 'Revived after 30,000 years in Siberian permafrost — and still infectious.'],
  ['plant-virus', 'Tobacco rattle virus', 'Tobacco rattle virus', '🌿', 'A rod-shaped virus that makes tobacco leaves rattle — and tulips streak.'],
  ['plant-virus2', 'Plum pox virus', 'Potyvirus plumpoxi', '🍑', 'The "sharka" virus that pockmarks plums across Europe.'],
  ['plant-virus3', 'Cauliflower mosaic virus', 'Cauliflower mosaic virus', '🥦', 'A DNA plant virus whose promoter powers half of plant genetic engineering.'],
  ['plant-virus4', 'Maize streak virus', 'Maize streak virus', '🌽', 'A twin-sphere geminivirus that paints yellow streaks across African maize.'],
  ['plant-virus5', 'Cucumber mosaic virus', 'Cucumber mosaic virus', '🥒', 'A tiny virus that infects over 1,200 plant species.'],
  ['plant-virus6', 'Turnip yellow mosaic virus', 'Tymovirus brassicae', '🥬', 'The first virus to reveal itself as a beautiful crystal.'],
  ['plant-virus7', 'Tomato spotted wilt virus', 'Orthotospovirus tomatomaculae', '🍅', 'A thrips-riding virus that wilts everything from tomatoes to peanuts.'],
  ['plant-virus8', 'Barley yellow dwarf virus', 'Luteovirus pavhordei', '🌾', 'Aphid-delivered, and the most damaging cereal virus on Earth.'],
  ['plant-virus-flexi', 'Potato virus X', 'Potato virus X', '🥔', 'A flexuous rod that quietly robs potato fields of their yield.'],
  ['viroid', 'Potato spindle tuber viroid', 'Potato spindle tuber viroid', '🥔', 'Not even a virus — a naked loop of RNA that still wrecks crops.'],
]
