// GrinKingdom seed rows — batch 2 (2026-09): 177 more species across all 8 kingdoms.
// Row format: [groupKey, name, sci, emoji, tagline, status?, size?, lifespan?]
// Included by scripts/gen-species.mjs as BATCH2_ROWS.

export const BATCH2_ROWS = [
  /* ── VIRUSES (+16) ── */
  ["alphavirus", "Chikungunya virus", "Chikungunya virus", "🦟", "A mosquito-borne virus whose name means \"that which bends up\" in Makua.|"],
  ["alphavirus", "Rocio virus", "Rocio virus", "🦟", "A South American alphavirus that shows up in the wet season.|"],
  ["alphavirus", "O'nyong-nyong virus", "O'nyong-nyong virus", "🦟", "An alphavirus whose African name means \"to shake\".|"],
  ["alphavirus", "Mayaro virus", "Mayaro virus", "🦟", "A joint-aching alphavirus named after a Venezuelan hill.|"],
  ["flavivirus", "Munin virus", "Munin virus", "🏝️", "A flavivirus that surfaced on a remote atoll in 1959.|"],
  ["flavivirus", "Kyasanur Forest disease virus", "Kyasanur Forest disease virus", "🐐", "A tick-borne fever first found in Karnataka forest, India.|"],
  ["hepevirus", "Hepatitis E virus", "Hepatitis E virus", "🍽️", "A waterborne liver virus that can be dangerous in pregnancy.|"],
  ["bunyavirus", "Andes orthohantavirus", "Andes orthohantavirus", "🐁", "A rodent-borne hantavirus that can pass from person to person.|"],
  ["bunyavirus", "Puumala orthohantavirus", "Puumala orthohantavirus", "🐭", "A common European hantavirus named after a Finnish city.|"],
  ["arenavirus", "Junin mammarenavirus", "Junin mammarenavirus", "🐀", "The first arenavirus found, named after a river in Argentina.|"],
  ["arenavirus", "Machupo mammarenavirus", "Machupo mammarenavirus", "🐀", "A rodent-borne fever virus from a Bolivian village.|"],
  ["calicivirus", "Canine calicivirus", "Canine calicivirus", "🐕", "A dog virus behind \"dry nose\" and mouth sores.|"],
  ["parvovirus", "Feline panleukopenia virus", "Feline panleukopenia virus", "🐈", "A tiny DNA virus that ravaged free-roaming cat colonies in the 1980s.|"],
  ["poxvirus", "Squirrelpox virus", "Squirrelpox virus", "🐿️", "A pox that spreads through city squirrels — and occasionally foxes.|"],
  ["giant-virus", "Cafeteriavirus massiliensis", "Cafeteriavirus massiliensis", "🍽️", "A giant virus named after a Marseille restaurant.|"],
  ["adenovirus", "Canine adenovirus 1", "Canine adenovirus 1", "🐶", "The adenovirus behind \"hard pad disease\" in dogs.|"],
  /* ── ARCHAEA (+9) ── */
  ["halophile", "Natronomonas pharaonis", "Natronomonas pharaonis", "🧂", "A pink salt-pond microbe from the Dead Sea.|"],
  ["methanogen-rod", "Methanobacterium arboriphilum", "Methanobacterium arboriphilum", "🌿", "The first methane-maker found growing on tree roots in boreal forests.|"],
  ["methanogen-sarcina", "Methanosarcina mazei", "Methanosarcina mazei", "🧊", "A Siberian methane-maker that survives deep freeze-thaw.|"],
  ["sulfolobus", "Sulfolobus tokodaii", "Sulfolobus tokodaii", "🌋", "A fast-growing hot-spring archaeon that doubles in ~70 minutes.|"],
  ["sulfolobus", "Metallosphaera sedula", "Metallosphaera sedula", "🌋", "A hot-spring coccus that helps dissolve copper and gold from ore.|"],
  ["pyrococcus", "Thermococcus barophilus", "Thermococcus barophilus", "🌊", "A deep-sea vent archaeon that thrives at 90 °C and crushing pressure.|"],
  ["thaumarchaeote", "Nitrosopumilus perichromatis", "Nitrosopumilus perichromatis", "🌊", "An ammonia-oxidizer from Antarctic sea-ice algae.|"],
  ["asgard", "Candidatus Parvarchaeum profundum", "Candidatus Parvarchaeum profundum", "🦠", "The \"small archaeon\" of deep-sea vents — a key clue to eukaryote origins.|"],
  ["archaeoglobus", "Archaeoglobus veneficus", "Archaeoglobus veneficus", "🌋", "A vent archaeon with a wider diet than its relatives.|"],
  /* ── BACTERIA (+19) ── */
  ["enteric", "Escherichia fergusonii", "Escherichia fergusonii", "🧫", "A gut-dwelling E. coli relative often found in water samples.|"],
  ["enteric", "Citrobacter freundii", "Citrobacter freundii", "🧫", "A gut bacterium that can turn a minor infection into a serious one.|"],
  ["enteric", "Hafnia alvei", "Hafnia alvei", "🧫", "A gut bacterium that thrives on milk sugars.|"],
  ["vibrio", "Vibrio alginolyticus", "Vibrio alginolyticus", "🌊", "A coastal bacterium that feeds on seaweed's algin.|"],
  ["pseudomonad", "Pseudomonas fluorescens", "Pseudomonas fluorescens", "🌿", "A soil bacterium that glows blue-green and guards plant roots.|"],
  ["pseudomonad", "Pseudomonas denitrificans", "Pseudomonas denitrificans", "🌿", "A soil bacterium that exhales nitrogen gas when oxygen runs low.|"],
  ["bacillus", "Bacillus megaterium", "Bacillus megaterium", "🧫", "A large, easy-to-grow soil bacterium — a protein-engineering workhorse.|"],
  ["bacillus", "Bacillus halodurans", "Bacillus halodurans", "🧂", "A salt-tolerant rod that thrives in the Dead Sea.|"],
  ["clostridium", "Clostridium acetobutylicum", "Clostridium acetobutylicum", "🏭", "The industrial bacterium that brews acetone and butanol for fuel.|"],
  ["clostridium", "Clostridium beijerinckii", "Clostridium beijerinckii", "🧫", "A spore-former that makes antibiotics and industrial solvents.|"],
  ["lactobacillus", "Lactobacillus plantarum", "Lactobacillus plantarum", "🥬", "The yogurt and sauerkraut workhorse of fermented vegetables.|"],
  ["lactobacillus", "Lactobacillus reuteri", "Lactobacillus reuteri", "🍼", "A human-gut lactobacillus named for a Swedish biochemist.|"],
  ["strep", "Streptococcus agalactiae", "Streptococcus agalactiae", "🐄", "Group B strep — usually harmless, serious for newborns.|"],
  ["staph", "Staphylococcus lugdunensis", "Staphylococcus lugdunensis", "🧫", "A skin staph with a disproportionate talent for heart-valve infections.|"],
  ["mycobacterium", "Mycobacterium bovis", "Mycobacterium bovis", "🐄", "The cattle strain of TB — the first TB bacterium humans feared.|"],
  ["rhizobium", "Sinorhizobium meliloti", "Sinorhizobium meliloti", "🌿", "The bacterium that turns alfalfa roots into nitrogen factories.|"],
  ["rhizobium", "Azotobacter vinelandii", "Azotobacter vinelandii", "🌿", "A free-living soil bacterium that fixes nitrogen without a plant partner.|"],
  ["cyano-filament", "Trichodesmium erythraeum", "Trichodesmium erythraeum", "🌊", "A floating blue-green filament that fertilises whole oceans.|"],
  ["geobacter", "Geobacter sulfurreducens", "Geobacter sulfurreducens", "⚗️", "A metal-eating bacterium that could power microbial batteries.|"],
  /* ── PROTISTS (+12) ── */
  ["ciliate", "Stylony mytilus", "Stylony mytilus", "🫧", "A stalked ciliate that flips its stalk like a tiny periscope.|"],
  ["dinoflagellate", "Gymnodinium catenatum", "Gymnodinium catenatum", "🌊", "A chain-forming dinoflagellate behind many red tides.|"],
  ["diatom", "Phaeodactylum tricornutum", "Phaeodactylum tricornutum", "🌊", "A three-horned diatom that is ocean science's favourite lab model.|"],
  ["euglenid", "Euglena viridis", "Euglena viridis", "🫧", "A green euglenid that photosynthesises by day and hunts bacteria by night.|"],
  ["green-alga", "Dunaliella salina", "Dunaliella salina", "🧂", "A salt-lake alga that turns ponds pink by storing beta-carotene.|"],
  ["green-alga-filament", "Oedogonium", "Oedogonium", "💧", "A filamentous pond alga that braids itself into green chains.|"],
  ["red-alga", "Gracilaria", "Gracilaria", "🌊", "The red alga behind the agar in your petri dishes.|"],
  ["brown-alga", "Ascophyllum nodosus", "Ascophyllum nodosus", "🌊", "A bladder-bearing seaweed that washes up on North Atlantic beaches.|"],
  ["slime-mold", "Stemonitis", "Stemonitis", "🍄", "The \"stalked slime moulds\" that rise as orange-topped forest columns.|"],
  ["radiolarian", "Thalassophyxis", "Thalassophyxis", "🌊", "A glass-skeleton radiolarian built like a tiny sea urchin.|"],
  ["piroplasm", "Theileria parva", "Theileria parva", "🐄", "A tick-borne parasite behind \"cattle fever\" of the African corridor.|"],
  ["babesia", "Babesia bovis", "Babesia bovis", "🐄", "A blood parasite that bores into cattle red cells and thrives.|"],
  /* ── FUNGI (+20) ── */
  ["mushroom-russula", "Russula virescens", "Russula virescens", "🍄", "The green-cracking russula that snaps audibly when stepped on.|"],
  ["mushroom-boletus", "Xerocomellus zelleri", "Xerocomellus zelleri", "🍄", "The cabbage-smelling brown bolete of beech woods.|"],
  ["mushroom-lactarius", "Lactarius resinosus", "Lactarius resinosus", "🍄", "The turkey-tail milkcap, a favourite autumn mushroom of Eastern Europe.|"],
  ["mushroom-chanterelle", "Cantharellus tubaeformis", "Cantharellus tubaeformis", "🍄", "The pale \"white chanterelle\" of mossy conifer forests.|"],
  ["mushroom-hygrocybe", "Hygrocybe miniata", "Hygrocybe miniata", "🍄", "A scarlet waxcap of heathland, so rare it has laws protecting it.|"],
  ["mushroom-coprinus", "Coprinopsis comata", "Coprinopsis comata", "🍄", "The shaggy inkcap — eat it young, then watch it ink itself away.|"],
  ["mushroom-hericium", "Hericium abietis", "Hericium abietis", "🍄", "The bearded tooth mushroom, a snowy puff on conifer stumps.|"],
  ["mushroom-mycena", "Mycena epipterygia", "Mycena epipterygia", "🍄", "The blue-veiled bonnet — a tiny, harmless mushroom with electric-blue gills.|"],
  ["coral", "Ramaria", "Ramaria", "🍄", "Branching coral fungi that look like miniature reef fragments.|"],
  ["stinkhorn", "Mutinus ravenelii", "Mutinus ravenelii", "🍄", "The snake-head stinkhorn, whose green cap smells of rot to recruit flies.|"],
  ["earthstar", "Geastrum inflatum", "Geastrum inflatum", "🍄", "The leathery earthstar that opens like a puffed star.|"],
  ["birdsnest", "Nidula candida", "Nidula candida", "🍄", "The white bird's-nest fungus, its \"eggs\" scattered by rain.|"],
  ["truffle", "Tuber brumale", "Tuber brumale", "🍄", "The winter white truffle of the Po Valley, foraged under oaks.|"],
  ["mushroom-morchella", "Morchella importuna", "Morchella importuna", "🍄", "The black morel, a honeycombed edible that rises after forest fires.|"],
  ["yeast", "Kluyveromyces lactis", "Kluyveromyces lactis", "🧫", "The industrial yeast that turns whey and sugars into useful chemicals.|"],
  ["yeast", "Pichia pastoris", "Pichia pastoris", "🧫", "The methylotrophic yeast that is a favourite factory for making proteins.|"],
  ["rust", "Puccinia straminea", "Puccinia straminea", "🌾", "Wheat stripe rust — the \"yellow\" that has caused famines across Asia.|"],
  ["jelly", "Tremella fuciformis", "Tremella fuciformis", "🍮", "The snow fungus — a white, brain-like jelly for Asian desserts and soups.|"],
  ["lichen-crust", "Caloplaca", "Caloplaca", "🪨", "The orange rock-paint lichen that colours cliffs and rooftops.|"],
  ["lichen-bushy", "Cladonia", "Cladonia", "❄️", "The tundra's reindeer moss — slow-growing and vital to caribou.|"],
  /* ── PLANTS (+49) ── */
  ["tree", "Corylus avellana", "Corylus avellana", "🌳", "The hazel, whose nuts are the base of a Mediterranean spread.|"],
  ["tree-rosaceae", "Prunus cerasus", "Prunus cerasus", "🍒", "The sour cherry tree, bred for pies and preserves rather than snacking.|"],
  ["tree-rutaceae", "Citrus paradisi", "Citrus paradisi", "🍊", "The grapefruit, an accidental cross that grew so big it needed a new name.|"],
  ["tree-rutaceae", "Citrus reticulata", "Citrus reticulata", "🍊", "The mandarin, the original small, easy-peel citrus of Asia.|"],
  ["tree-sapindaceae", "Carica papaya", "Carica papaya", "🥭", "The papaya, a tropical tree that fruits in weeks, not years.|"],
  ["mangrove", "Avicennia marina", "Avicennia marina", "🌊", "The grey mangrove, a salt-excreting species that breathes through its roots.|"],
  ["cypress", "Cupressus macrocarpa", "Cupressus macrocarpa", "🌲", "The Monterey cypress, windswept sentinel of Big Sur cliffs.|"],
  ["flower-asteraceae", "Echinacea purpurea", "Echinacea purpurea", "🌼", "The purple coneflower, a prairie bloom with a long folk-medicine history.|"],
  ["flower-campanulaceae", "Lobelia erinus", "Lobelia erinus", "💠", "The trailing lobelia, a tiny blue that edges every summer window.|"],
  ["flower-rosaceae", "Rosa damascena", "Rosa damascena", "🌹", "The damask rose, the rose of old perfumes, pressed for attar oil.|"],
  ["flower-fabaceae", "Trifolium repens", "Trifolium repens", "🌿", "White clover, a ground-hugging legume that feeds bees and fixes nitrogen.|"],
  ["flower-solanaceae", "Petunia hybrida", "Petunia hybrida", "🌸", "The garden petunia, a South American weed bred into a colour machine.|"],
  ["flower-solanaceae", "Datura stramonium", "Datura stramonium", "🌿", "Jimsonweed, a ghostly night-flower with a dangerous history.|"],
  ["flower-apiaceae", "Anethum graveolens", "Anethum graveolens", "🌿", "Dill, the frilly herb that seasons pickles since Roman times.|"],
  ["flower-ranunculaceae", "Anemone nemorosa", "Anemone nemorosa", "🌸", "The wood anemone, a spring flower that nods in the breeze.|"],
  ["flower-ranunculaceae", "Clematis vitalba", "Clematis vitalba", "🌸", "The old man's beard, a vine whose feathery seeds drift on the wind.|"],
  ["flower-ranunculaceae", "Aquilegia vulgaris", "Aquilegia vulgaris", "🌸", "The columbine, a spurred flower bees can barely reach into.|"],
  ["flower-liliaceae", "Fritillaria imperialis", "Fritillaria imperialis", "👑", "The crown imperial, an orange flower that wears a crown of leaves.|"],
  ["flower-orchidaceae", "Cymbidium", "Cymbidium", "🌸", "The boat orchids, grand orchids of East Asian hillsides.|"],
  ["flower-asphodelaceae", "Haworthia", "Haworthia", "🪴", "The zebra plant, a windowsill succulent with striped leaves.|"],
  ["flower-bromeliaceae", "Guzmania", "Guzmania", "🌸", "The gumnium bromeliads with flame-red centres that last for months.|"],
  ["flower-zingiberaceae", "Alpinia zerumbet", "Alpinia zerumbet", "🌸", "Shell ginger, a garden ginger with seashell-shaped blooms.|"],
  ["flower-geraniaceae", "Pelargonium × hortorum", "Pelargonium", "🌸", "The garden geraniums, balcony plants of the Victorian age.|"],
  ["flower-begoniaceae", "Begonia maculata", "Begonia maculata", "🌸", "The polka-dot begonia, a houseplant with moonlit-sky leaves.|"],
  ["flower-primulaceae", "Oenothera biennis", "Oenothera biennis", "🌼", "The evening primrose, a flower that opens after sunset.|"],
  ["flower-gentianaceae", "Gentiana lutea", "Gentiana lutea", "💙", "The great yellow gentian, a deep-coloured alpine meadow flower.|"],
  ["flower-gentianaceae", "Myosotis sylvatica", "Myosotis sylvatica", "💙", "The forget-me-not, a tiny blue flower that keeps its name across languages.|"],
  ["flower-apocynaceae", "Vinca minor", "Vinca minor", "💙", "The lesser periwinkle, evergreen groundcover with sky-blue flowers.|"],
  ["flower-crassulaceae", "Echeveria elegans", "Echeveria elegans", "🪴", "The hen and chicks, a rosette succulent that looks like a flower.|"],
  ["flower-cactaceae", "Mammillaria", "Mammillaria", "🌵", "The pincushion cacti, clusters of thorny buttons with pink flowers.|"],
  ["flower-amaranthaceae", "Celosia", "Celosia", "🌸", "The cockscomb, a flower with crests like combs and flames.|"],
  ["flower-aizoaceae", "Lithops", "Lithops", "🪨", "The living stones, succulents so camouflaged you'll walk over them.|"],
  ["flower-polygonaceae", "Rumex", "Rumex", "🌿", "The dock, a humble roadside plant whose leaves once dressed salads.|"],
  ["succulent-euphorbia", "Euphorbia milii", "Euphorbia milii", "🪴", "The crown of thorns, a thorny succulent blooming crimson at Christmas.|"],
  ["grass", "Panicum miliaceum", "Panicum miliaceum", "🌾", "Millet, an ancient grain that feeds birds and people alike.|"],
  ["grass", "Andropogon gerardii", "Andropogon gerardii", "🌾", "Big bluestem, the prairie grass that turns gold in autumn.|"],
  ["bamboo", "Dendrocalamus giganteus", "Dendrocalamus giganteus", "🎋", "Giant bamboo, a woody grass that can shoot up a metre a day.|"],
  ["grass-cyperaceae", "Carex", "Carex", "🌿", "The sedges, grass-like plants of damp ground — \"sedges like swedes\".|"],
  ["fern", "Cyrtomium falcatum", "Cyrtomium falcatum", "🌿", "The Japanese holly fern, an evergreen frond for shady spots.|"],
  ["fern", "Dryopteris", "Dryopteris", "🌿", "The wood ferns, the common ferns of temperate forests.|"],
  ["fern", "Polystichum", "Polystichum", "🌿", "The shield ferns, tough evergreen ferns named for their basal shield.|"],
  ["horsetail", "Equisetum hyemale", "Equisetum hyemale", "🌿", "The scouring-rush, a horsetail once used to polish copper.|"],
  ["clubmoss", "Selaginella", "Selaginella", "🌿", "The spikemosses, living fossils that reinvent rain colour.|"],
  ["moss", "Polytrichum", "Polytrichum", "🌿", "Haircap moss, the tall moss of peat bogs — a forest in miniature.|"],
  ["moss", "Bryum", "Bryum", "🌿", "Common moss, the carpet of lawns and pavement with no flowers at all.|"],
  ["sphagnum", "Sphagnum", "Sphagnum", "🌿", "Peat moss, the bog moss that stores carbon for millennia.|"],
  ["liverwort", "Marchantia", "Marchantia", "🌿", "The common liverwort, a flat thallus with a tiny umbrella for sex.|"],
  ["liverwort", "Conocephalum", "Conocephalum", "🌿", "The bladderwort liverwort, a forest-floor lichen that looks like little boats.|"],
  ["hornwort", "Anthoceros", "Anthoceros", "🌿", "The hornworts, moss relatives whose fruit is a tiny green horn.|"],
  /* ── ANIMALS (+49) ── */
  ["pinniped", "Bearded seal", "Erignathus barbatus", "🦭", "The whiskered ice seal that hunts on the Arctic bottom."],
  ["pinniped", "Ross seal", "Ommatophoca rossii", "🦭", "The silent seal of the pack ice, still rarely seen alive."],
  ["giraffe", "Masai giraffe", "Giraffa tippelskirchi", "🦒", "The jagged-patched giant of the East African savanna."],
  ["camelid", "Bactrian camel", "Camelus bactrianus", "🐫", "The two-humped desert freighter of Central Asia."],
  ["eulipotyphlan-shrew", "Common shrew", "Sorex araneus", "🐭", "The sparrow-sized mammal with a heart that beats 800 times a minute."],
  ["bird-shore", "Grey wagtail", "Motacilla cinerea", "🐦", "The flicking-tail wader of every riverside."],
  ["bird-heron", "Great blue heron", "Ardea herodias", "🐦", "The towering wading bird of North American wetlands."],
  ["snake-colubrid", "Eastern kingsnake", "Lampropeltis getula", "🐍", "The snake that eats other snakes — immunity included."],
  ["snake-python", "Indian python", "Python molurus", "🐍", "The 5-metre constrictor of the Indian subcontinent.", "Endangered"],
  ["snake-viper", "Eastern diamondback", "Crotalus adamanteus", "🐍", "The large rattlesnake of the southeastern pine flats."],
  ["lizard-basilisk", "Common basilisk", "Basiliscus basiliscus", "🦎", "The \"Christo lizard\" that runs across water."],
  ["shark", "Grey reef shark", "Carcharhinus amblyrhynchos", "🦈", "The common reef patroller that hangs at the edge of the drop-off."],
  ["crab-true", "European brown crab", "Cancer pagurus", "🦀", "The \"slab\" crab of the European North Sea, a staple of the pot."],
  ["crab-swimming", "Blue swimmer crab", "Portunus pelagicus", "🦀", "The blue-armed crab that swims like a tiny jet."],
  ["myriapod-centipede", "Giant land centipede", "Scolopendra heros", "🐛", "The 30-cm centipede of the Central American forests."],
  ["anemone", "Bubble-tip anemone", "Entacmaea quadricolor", "🪸", "The \"Nemo\" anemone, home to the clownfish."],
  ["worm-rag", "Ragworm", "Arenicola marina", "🪱", "The \"lugworm\" that is the classic fishing bait of the North Sea."],
  ["flatworm-planarian", "Giant planarian", "Dugesia japonica", "🪱", "The flatworm that can regenerate a whole head from a slice."],
  ["bee-solitary", "Blue mason bee", "Osmia lanceolata", "🐝", "The \"blue\" mason bee that builds its nest from mud pellets."],
  ["wasp-social", "German yellowjacket", "Vespula germanica", "🐝", "The yellowjacket of the picnic table, a sting to remember."],
  ["hyena", "Spotted hyena", "Crocuta crocutus", "🐺", "The laughing hyena — a pack-hunting scavenger of the African savanna."],
  ["hyena", "Brown hyena", "Hyaena brachyura", "🐺", "The quiet, solitary hyena of the deserts and steppes."],
  ["smallcat", "Jaguarundi", "Herpailurus yagouaroundi", "🐱", "The reddish, long-bodied cat of the Americas."],
  ["smallcat", "European wildcat", "Felis silvestris", "🐱", "The shaggy ancestor of every house cat."],
  ["mustelid", "American mink", "Neovison vison", "🦦", "The sleek river otter of furs, a mustelid by blood."],
  ["mustelid", "Long-tailed weasel", "Mustela frenata", "🦡", "The \"ermine\" of North America, a streak of white in winter."],
  ["mustelid", "American marten", "Martes americanus", "🦡", "The tree-climbing mustelid of the boreal forest."],
  ["procyonid", "Raccoon", "Procyon lotor", "🦝", "The masked bandit with the dexterity of hands."],
  ["procyonid", "Coati", "Nasua nasua", "🦝", "The long-nosed, stripy raccoon relative of the Neotropics."],
  ["procyonid", "Kinkajou", "Potos flavus", "🦝", "The golden \"honey bear\" that drips nectar from its face."],
  ["viverrid", "African civet", "Civettictis civetta", "🐈", "The striped cat-musk animal — source of the perfume musk."],
  ["viverrid", "Small-spotted genet", "Genetta genetta", "🐈", "The rosette-spotted, ring-tailed cat of the Mediterranean scrub."],
  ["viverrid", "Yellow mongoose", "Cynictis penicillata", "🦎", "The \"capped\" mongoose, famous for standing guard against cobras."],
  ["bovid", "Sitatunga", "Tragelaphus spekei", "🦌", "The swamp antelope with spiralled horns."],
  ["bovid", "Dama gazelle", "Nanger dama", "🦌", "The \"Arabian oryx\" that was driven extinct in the wild.", "Extinct in the Wild"],
  ["equid", "Donkey", "Equus asinus", "🐴", "The \"donkey\", the pack animal that carries the world."],
  ["primate-monkey", "Black howler", "Alouatta caraya", "🐒", "The \"black howler\", whose roar carries for 3 km."],
  ["lemur", "Fossa", "Cryptoprocta ferox", "🐈", "The \"fossa\", Madagascar's largest predator."],
  ["dolphin", "Commerson's dolphin", "Cephalorhynchus commersonii", "🐬", "The \"Commerson's\" dolphin, black and white with a white collar."],
  ["dolphin", "Indo-Pacific humpback dolphin", "Sousa chinensis", "🐬", "The \"humpback\" dolphin, a gray dolphin of the Indo-Pacific."],
  ["shark", "Thresher shark", "Alopias superciliosus", "🦈", "The \"thresher\" shark, which hunts with a tail longer than its body."],
  ["fish-percoid", "Clown triggerfish", "Balistoides conspicillum", "🐠", "The \"clown\" triggerfish, a colorful reef dweller."],
  ["fish-percoid", "Parrotfish", "Scarus frenatus", "🐠", "The \"parrot\" fish, which \"chews\" coral to make sand."],
  ["bivalve-scallop", "Queen scallop", "Aequipecten opercularis", "🐚", "The \"queen\" scallop, a \"famous\" scallop of the North Atlantic."],
  ["bee-social", "Carpenter bee", "Xylocopa virginica", "🐝", "The \"carpenter\" bee, which \"bores\" holes in wood to nest."],
  ["insect-mayfly", "Common mayfly", "Ephoron virgo", "🪰", "The \"mayfly\", an \"aquatic\" insect that \"lives\" for a day."],
  ["insect-caddis", "Common caddisfly", "Rhyacophila filicornis", "🪰", "The \"caddisfly\", a \"mayfly-like\" insect of the stream."],
  ["bug-assassin", "Assassin bug", "Reduvius personatus", "🪲", "The \"assassin\" bug, a \"predatory\" bug of the house."],
  ["bug-shield", "Shield bug", "Nezara viridula", "🪲", "The \"green shield\" bug, a \"green\" bug of the garden."],
  /* ── HUMANS (+3) ── */
  ["hominin-homo", "Homo rhodesiensis", "Homo rhodesiensis", "🦴", "The \"Broken Hill Man\", a robust early Homo from a cave in Zambia.|"],
  ["australopith", "Australopithecus garhi", "Australopithecus garhi", "🦴", "A 2.5-million-year-old australopith found beside butchered antelope.|"],
  ["kenyanthropus", "Kenyanthropus platyops", "Kenyanthropus platyops", "🦴", "A flat-faced human ancestor from Lake Turkana, 3.5 million years old.|"],
]
